package io.mazewall.core

/**
 * Utility to map common POSIX/Linux error numbers to their symbolic names.
 */
public object ErrnoMapping {
    private val NAMES = mapOf(
        1 to "EPERM",
        2 to "ENOENT",
        3 to "ESRCH",
        4 to "EINTR",
        5 to "EIO",
        6 to "ENXIO",
        7 to "E2BIG",
        8 to "ENOEXEC",
        9 to "EBADF",
        10 to "ECHILD",
        11 to "EAGAIN", // EWOULDBLOCK is also 11
        12 to "ENOMEM",
        13 to "EACCES",
        14 to "EFAULT",
        15 to "ENOTBLK",
        16 to "EBUSY",
        17 to "EEXIST",
        18 to "EXDEV",
        19 to "ENODEV",
        20 to "ENOTDIR",
        21 to "EISDIR",
        22 to "EINVAL",
        23 to "ENFILE",
        24 to "EMFILE",
        25 to "ENOTTY",
        26 to "ETXTBSY",
        27 to "EFBIG",
        28 to "ENOSPC",
        29 to "ESPIPE",
        30 to "EROFS",
        31 to "EMLINK",
        32 to "EPIPE",
        33 to "EDOM",
        34 to "ERANGE",
        35 to "EDEADLK", // EDEADLOCK is also 35
        36 to "ENAMETOOLONG",
        37 to "ENOLCK",
        38 to "ENOSYS",
        39 to "ENOTEMPTY",
        40 to "ELOOP",
        42 to "ENOMSG",
        43 to "EIDRM",
        44 to "ECHRNG",
        45 to "EL2NSYNC",
        46 to "EL3HLT",
        47 to "EL3RST",
        48 to "ELNRNG",
        49 to "EUNATCH",
        50 to "ENOCSI",
        51 to "EL2HLT",
        52 to "EBADE",
        53 to "EBADR",
        54 to "EXFULL",
        55 to "ENOANO",
        56 to "EBADRQC",
        57 to "EBADSLT",
        59 to "EBFONT",
        60 to "ENOSTR",
        61 to "ENODATA",
        62 to "ETIME",
        63 to "ENOSR",
        64 to "ENONET",
        65 to "ENOPKG",
        66 to "EREMOTE",
        67 to "ENOLINK",
        68 to "EADV",
        69 to "ESRMNT",
        70 to "ECOMM",
        71 to "EPROTO",
        72 to "EMULTIHOP",
        73 to "EDOTDOT",
        74 to "EBADMSG",
        75 to "EOVERFLOW",
        76 to "ENOTUNIQ",
        77 to "EBADFD",
        78 to "EREMCHG",
        79 to "ELIBACC",
        80 to "ELIBBAD",
        81 to "ELIBSCN",
        82 to "ELIBMAX",
        83 to "ELIBEXEC",
        84 to "EILSEQ",
        85 to "ERESTART",
        86 to "ESTRPIPE",
        87 to "EUSERS",
        88 to "ENOTSOCK",
        89 to "EDESTADDRREQ",
        90 to "EMSGSIZE",
        91 to "EPROTOTYPE",
        92 to "ENOPROTOOPT",
        93 to "EPROTONOSUPPORT",
        94 to "ESOCKTNOSUPPORT",
        95 to "EOPNOTSUPP", // ENOTSUP is also 95
        96 to "EPFNOSUPPORT",
        97 to "EAFNOSUPPORT",
        98 to "EADDRINUSE",
        99 to "EADDRNOTAVAIL",
        100 to "ENETDOWN",
        101 to "ENETUNREACH",
        102 to "ENETRESET",
        103 to "ECONNABORTED",
        104 to "ECONNRESET",
        105 to "ENOBUFS",
        106 to "EISCONN",
        107 to "ENOTCONN",
        108 to "ESHUTDOWN",
        109 to "ETOOMANYREFS",
        110 to "ETIMEDOUT",
        111 to "ECONNREFUSED",
        112 to "EHOSTDOWN",
        113 to "EHOSTUNREACH",
        114 to "EALREADY",
        115 to "EINPROGRESS",
        116 to "ESTALE",
        117 to "EUCLEAN",
        118 to "ENOTNAM",
        119 to "ENAVAIL",
        120 to "EISNAM",
        121 to "EREMOTEIO",
        122 to "EDQUOT",
        123 to "ENOMEDIUM",
        124 to "EMEDIUMTYPE",
        125 to "ECANCELED",
        126 to "ENOKEY",
        127 to "EKEYEXPIRED",
        128 to "EKEYREVOKED",
        129 to "EKEYREJECTED",
        130 to "EOWNERDEAD",
        131 to "ENOTRECOVERABLE",
        132 to "ERFKILL",
        133 to "EHWPOISON"
    )

    /**
     * Returns the symbolic name for a given POSIX errno, or null if unknown.
     */
    public fun getSymbolicName(errno: Int): String? {
        return NAMES[errno]
    }
}
