services:
    unprotected:
        build:
            context: ../../
            dockerfile: demo/vulnerable-app/Containerfile
        ports:
            - "8082:8080"
        environment:
            - MAZEWALL_ENABLED=false
        annotations:
            io.podman.annotations.seccomp: ${PWD}/../../podman-seccomp.json

    protected:
        build:
            context: ../../
            dockerfile: demo/vulnerable-app/Containerfile
        environment:
            - MAZEWALL_ENABLED=true
            - SERVER_PORT=8081
        annotations:
            io.podman.annotations.seccomp: ${PWD}/../../podman-seccomp.json
        cap_add:
            - SYS_ADMIN
            - AUDIT_READ
        network_mode: host
        userns_mode: host
