@startuml Enforcer Class Diagram
!pragma useIntermediatePackages false
!theme spacelab
set separator none
hide empty members

class "BpfFilter" as io.mazewall.BpfFilter {
  + {static}BpfFilter INSTANCE
  + {static}int SECCOMP_DATA_NR_OFFSET
  + {static}int SECCOMP_DATA_ARCH_OFFSET
  __
  +List<BpfInstruction> build(Arch, Policy<?, ?>, boolean)
  +void emitInspections$io_mazewall_enforcer(Builder, List<SyscallInspection>, boolean, Set<Integer>)
}
class "LinuxNative" as io.mazewall.LinuxNative {
  + {static}LinuxNative INSTANCE
  __
  +void setEngine(NativeEngine)
  +void resetToDefault()
  +NativeTransaction getTRANSACTION_INSTANCE()
  +T withTransaction(Function1<? super NativeTransaction, ? extends T>)
  +NativeFileSystem getFileSystem()
  +NativeNetworking getNetworking()
  +NativeProcess getProcess()
  +NativeMemory getMemory()
  +SyscallResult prctl(NativeTransaction, int, Object, Object, Object, Object)
  +SyscallResult syscall(NativeTransaction, long, Object, Object, Object, Object, Object, Object)
  +SyscallResult syscall4(NativeTransaction, long, Object, Object, Object, Object)
  +SyscallResult open(NativeTransaction, MemorySegment, int)
  +SyscallResult close-LsA-840(int)
  +SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  +SyscallResult socket(NativeTransaction, int, int, int)
  +SyscallResult bind-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult listen-cRJsZIA(NativeTransaction, int, int)
  +SyscallResult accept-r9EpL9Y(NativeTransaction, int, MemorySegment, MemorySegment)
  +SyscallResult connect-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult sendmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult recvmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, MemorySegment)
  +SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, long)
  +SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  +SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
  +SyscallResult read-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  +SyscallResult write-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  +SyscallResult recv-cNv3Vh8(NativeTransaction, int, MemorySegment, long, int)
  +SyscallResult fcntl-r9EpL9Y(NativeTransaction, int, int, long)
  +int gettid()
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
  +MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
interface "NativeEngine" as io.mazewall.NativeEngine {
  + {abstract}SyscallResult syscall(NativeTransaction, long, Object, Object, Object, Object, Object, Object)
  + {abstract}SyscallResult syscall4(NativeTransaction, long, Object, Object, Object, Object)
  + {abstract}SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, MemorySegment)
  + {abstract}SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, long)
  + {abstract}SyscallResult fcntl-r9EpL9Y(NativeTransaction, int, int, long)
  + {abstract}SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
interface "NativeFileSystem" as io.mazewall.NativeFileSystem {
  + {abstract}SyscallResult open(NativeTransaction, MemorySegment, int)
  + {abstract}SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
  + {abstract}SyscallResult close-LsA-840(int)
}
interface "NativeMemory" as io.mazewall.NativeMemory {
  + {abstract}SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  + {abstract}SyscallResult read-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  + {abstract}SyscallResult write-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  + {abstract}MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
interface "NativeNetworking" as io.mazewall.NativeNetworking {
  + {abstract}SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  + {abstract}SyscallResult socket(NativeTransaction, int, int, int)
  + {abstract}SyscallResult bind-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  + {abstract}SyscallResult listen-cRJsZIA(NativeTransaction, int, int)
  + {abstract}SyscallResult accept-r9EpL9Y(NativeTransaction, int, MemorySegment, MemorySegment)
  + {abstract}SyscallResult connect-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  + {abstract}SyscallResult sendmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  + {abstract}SyscallResult recvmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  + {abstract}SyscallResult recv-cNv3Vh8(NativeTransaction, int, MemorySegment, long, int)
}
interface "NativeProcess" as io.mazewall.NativeProcess {
  + {abstract}int gettid()
  + {abstract}SyscallResult prctl(NativeTransaction, int, Object, Object, Object, Object)
}
interface "NativeTransaction" as io.mazewall.NativeTransaction {
}
class "Platform" as io.mazewall.Platform {
  + {static}Platform INSTANCE
  __
  +boolean isLinux()
  +boolean isSupported()
  +boolean isArchitectureSupported$io_mazewall_enforcer()
  +FallbackBehavior configuredFallback()
  +String getYamaPath$io_mazewall_enforcer()
  +void setYamaPath$io_mazewall_enforcer(String)
  +Diagnostics diagnose()
}
class "Policy" as io.mazewall.Policy<S extends PolicyScope, State extends PolicyState> {
  + {static}Companion Companion
  + {static}Policy<ProcessWideSafe, Uncompiled> PURE_COMPUTE_UNSAFE
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_EXEC
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_NETWORK
  + {static}Policy<ThreadLocalOnly, Uncompiled> PURE_COMPUTE
  __
  +SeccompAction getDefaultAction()
  +Map<Syscall, SeccompAction> getSyscallActions()
  +boolean getAllowMmapExec()
  +boolean getAllowNonThreadClone()
  +boolean getAllowUnsafePrctl()
  +Set<SandboxedPath> getAllowedFsReadPaths()
  +Set<SandboxedPath> getAllowedFsWritePaths()
  +boolean getEnforceLandlock$io_mazewall_enforcer()
  +List<BpfInstruction> getCompiledFilters()
  +boolean isSyscallAllowed(Syscall)
  +Map<Integer, SeccompAction> syscallActionNumbers(Arch)
  + {static}Builder builder()
  + {static}Builder threadLocalBuilder()
}
class "PolicyKt" as io.mazewall.PolicyKt {
  + {static}Policy<S, Compiled> compile(Policy<? extends S, ? extends Uncompiled>, Arch)
  + {static}Policy<ProcessWideSafe, Uncompiled> plus(Policy<? extends ProcessWideSafe, ? extends Uncompiled>, Policy<? extends ProcessWideSafe, ? extends Uncompiled>)
  + {static}Policy<ThreadLocalOnly, Uncompiled> plusThreadLocal(Policy<?, ? extends Uncompiled>, Policy<? extends ThreadLocalOnly, ? extends Uncompiled>)
  + {static}Policy<ThreadLocalOnly, Uncompiled> plusThreadLocalReverse(Policy<? extends ThreadLocalOnly, ? extends Uncompiled>, Policy<? extends ProcessWideSafe, ? extends Uncompiled>)
}
interface "PolicyScope" as io.mazewall.PolicyScope {
}
interface "PolicyState" as io.mazewall.PolicyState {
}
class "RealNativeEngine" as io.mazewall.RealNativeEngine {
  + {static}RealNativeEngine INSTANCE
  __
  +SyscallResult prctl(NativeTransaction, int, Object, Object, Object, Object)
  +SyscallResult syscall(NativeTransaction, long, Object, Object, Object, Object, Object, Object)
  +SyscallResult syscall4(NativeTransaction, long, Object, Object, Object, Object)
  +SyscallResult open(NativeTransaction, MemorySegment, int)
  +SyscallResult close-LsA-840(int)
  +SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  +SyscallResult socket(NativeTransaction, int, int, int)
  +SyscallResult bind-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult listen-cRJsZIA(NativeTransaction, int, int)
  +SyscallResult accept-r9EpL9Y(NativeTransaction, int, MemorySegment, MemorySegment)
  +SyscallResult connect-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult sendmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult recvmsg-r9EpL9Y(NativeTransaction, int, MemorySegment, int)
  +SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, MemorySegment)
  +SyscallResult ioctl-r9EpL9Y(NativeTransaction, int, long, long)
  +SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  +SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
  +SyscallResult read-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  +SyscallResult write-r9EpL9Y(NativeTransaction, int, MemorySegment, long)
  +SyscallResult recv-cNv3Vh8(NativeTransaction, int, MemorySegment, long, int)
  +SyscallResult fcntl-r9EpL9Y(NativeTransaction, int, int, long)
  +int gettid()
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
  +MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
class "SbobParser" as io.mazewall.SbobParser {
  + {static}SbobParser INSTANCE
  __
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(Path, Policy<?, ? extends Uncompiled>)
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(InputStream, Policy<?, ? extends Uncompiled>)
  +Policy<ThreadLocalOnly, Uncompiled> parseJsonToPolicy(String, Policy<?, ? extends Uncompiled>)
}
interface "SeccompMode" as io.mazewall.SeccompMode {
}
interface "YamaPtraceScope" as io.mazewall.YamaPtraceScope {
}
class "Errno" as io.mazewall.core.Errno {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "FileDescriptor" as io.mazewall.core.FileDescriptor {
  +int getFd()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "SandboxedPath" as io.mazewall.core.SandboxedPath {
  + {static}Companion Companion
  __
  +String getValue()
  + {static}String toString-impl(String)
  + {static}int hashCode-impl(String)
  + {static}boolean equals-impl(String, Object)
  + {static}boolean equals-impl0(String, String)
  + {static}String of-NptRyN4(String, boolean)
}
enum "SeccompAction" as io.mazewall.core.SeccompAction {
  ACT_KILL_PROCESS
  ACT_KILL_THREAD
  ACT_TRAP
  ACT_ERRNO
  ACT_NOTIFY
  ACT_LOG
  ACT_ALLOW
  __
  +int getPriority()
  +int getNativeCode()
}
class "SyscallNumber" as io.mazewall.core.SyscallNumber {
  +int getNr()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "ContainedExecutors" as io.mazewall.enforcer.ContainedExecutors {
  ..
  + {static}ContainedExecutors INSTANCE
  __
  +void installOnCurrentThread(Policy<?, ? extends Uncompiled>[])
  +void installOnProcess(Policy<? extends ProcessWideSafe, ? extends Uncompiled>[])
  +ExecutorService wrap(ExecutorService, Policy<?, ? extends Uncompiled>[])
}
class "ContainerStateRegistry" as io.mazewall.enforcer.ContainerStateRegistry {
  + {static}ContainerStateRegistry INSTANCE
  __
  +Map<Syscall, SeccompAction> getThreadSyscallActions()
  +void setThreadSyscallActions(Map<Syscall, ? extends SeccompAction>)
  +SeccompAction getThreadDefaultAction()
  +void setThreadDefaultAction(SeccompAction)
  +boolean getThreadAllowsMmapExec()
  +void setThreadAllowsMmapExec(boolean)
  +boolean getThreadAllowsNonThreadClone()
  +void setThreadAllowsNonThreadClone(boolean)
  +boolean getThreadAllowsUnsafePrctl()
  +void setThreadAllowsUnsafePrctl(boolean)
  +Set<Syscall> getThreadAllowedSyscalls()
  +void setThreadAllowedSyscalls(Set<? extends Syscall>)
  +int getFilterDepth()
  +void setFilterDepth(int)
  +Set<SandboxedPath> getThreadLandlockAppliedReads()
  +void setThreadLandlockAppliedReads(Set<SandboxedPath>)
  +Set<SandboxedPath> getThreadLandlockAppliedWrites()
  +void setThreadLandlockAppliedWrites(Set<SandboxedPath>)
  +Map<Syscall, SeccompAction> getPROCESS_SYSCALL_ACTIONS()
  +AtomicReference<SeccompAction> getPROCESS_DEFAULT_ACTION()
  +AtomicBoolean getPROCESS_ALLOWS_MMAP_EXEC()
  +AtomicBoolean getPROCESS_ALLOWS_NON_THREAD_CLONE()
  +AtomicBoolean getPROCESS_ALLOWS_UNSAFE_PRCTL()
  +AtomicReference<Set<Syscall>> getPROCESS_ALLOWED_SYSCALLS()
  +AtomicInteger getPROCESS_FILTER_DEPTH()
}
class "ContainmentViolationDetector" as io.mazewall.enforcer.ContainmentViolationDetector {
  + {static}ContainmentViolationDetector INSTANCE
  __
  +String[] getDENIED_PHRASES()
  +boolean isContainmentViolation(Throwable)
  +Throwable findViolationCause(Throwable)
}
class "ContainmentViolationException" as io.mazewall.enforcer.ContainmentViolationException {
}
class "FilterInstallationPlanner" as io.mazewall.enforcer.FilterInstallationPlanner {
  + {static}FilterInstallationPlanner INSTANCE
  __
  +FilterPlan calculateNewFilter(Policy<?, ? extends Uncompiled>, ContainerState)
  +void verifyFilterDepth(int)
}
class "JvmFloorWorkload" as io.mazewall.enforcer.JvmFloorWorkload {
  + {static}JvmFloorWorkload INSTANCE
  __
  +void run()
  + {static}void main(String[])
}
class "ThreadLocalDelegate" as io.mazewall.enforcer.ThreadLocalDelegate<T> {
  +T getValue(Object, KProperty<?>)
  +void setValue(Object, KProperty<?>, T)
}
class "ThreadLocalDelegateKt" as io.mazewall.enforcer.ThreadLocalDelegateKt {
  + {static}ThreadLocalDelegate<T> threadLocal(Function0<? extends T>)
}
class "ValidationKt" as io.mazewall.enforcer.ValidationKt {
  + {static}void validateLinuxAndNotVirtual()
}
class "ContainedExecutorWrapper" as io.mazewall.enforcer.internal.ContainedExecutorWrapper {
  +void execute(Runnable)
  +Future<T> submit(Callable<T>)
  +Future<T> submit(Runnable, T)
  +Future<?> submit(Runnable)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>, long, TimeUnit)
  +T invokeAny(Collection<? extends Callable<T>>)
  +T invokeAny(Collection<? extends Callable<T>>, long, TimeUnit)
  +void close()
  +void shutdown()
  +List<Runnable> shutdownNow()
  +boolean isShutdown()
  +boolean isTerminated()
  +boolean awaitTermination(long, TimeUnit)
}
class "LayoutValidator" as io.mazewall.ffi.LayoutValidator {
  + {static}LayoutValidator INSTANCE
  __
  +void validate()
}
class "Landlock" as io.mazewall.landlock.Landlock {
  + {static}Landlock INSTANCE
  + {static}long LANDLOCK_ACCESS_FS_EXECUTE
  + {static}long LANDLOCK_ACCESS_FS_WRITE_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_FILE
  + {static}long LANDLOCK_ACCESS_FS_MAKE_CHAR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_DIR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_REG
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_FIFO
  + {static}long LANDLOCK_ACCESS_FS_MAKE_BLOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SYM
  + {static}long LANDLOCK_ACCESS_FS_REFER
  + {static}long LANDLOCK_ACCESS_FS_TRUNCATE
  + {static}long LANDLOCK_ACCESS_FS_IOCTL_DEV
  __
  +void applyRestrictiveBarrier()
  +boolean isSupported()
  +int getAbiVersion()
  +void applyRuleset(Policy<?, ? extends Uncompiled>)
  +long getFullAccessMask$io_mazewall_enforcer(int)
  +void handleUnsupportedLandlock$io_mazewall_enforcer()
  +void addJvmClasspathRules-cRJsZIA$io_mazewall_enforcer(Arena, int, long)
  +void enforceRuleset-LsA-840$io_mazewall_enforcer(int)
  +void applyUserRules-cNv3Vh8$io_mazewall_enforcer(Arena, int, Policy<?, ?>, int, long)
  +long getAccessMask$io_mazewall_enforcer(int, Policy<?, ?>)
  +SyscallResult createRuleset$io_mazewall_enforcer(Arena, long, int)
}
class "LandlockSession" as io.mazewall.landlock.LandlockSession {
  +LandlockState getState()
  +void applyRuleset()
}
interface "LandlockState" as io.mazewall.landlock.LandlockState {
}
interface "ArgCheck" as io.mazewall.seccomp.ArgCheck {
}
abstract class "BpfInstruction" as io.mazewall.seccomp.BpfInstruction {
  + {static}Companion Companion
  __
  + {abstract}short getCode()
  + {abstract}short getJt()
  + {abstract}short getJf()
  + {abstract}int getK()
}
interface "BpfMacro" as io.mazewall.seccomp.BpfMacro {
}
class "BpfProgram" as io.mazewall.seccomp.BpfProgram {
  + {static}Companion Companion
  __
  +List<BpfInstruction> getInstructions()
  + {static}Builder builder()
  + {static}BpfProgram dsl(Consumer<Builder>)
}
class "PureJavaBpfEngine" as io.mazewall.seccomp.PureJavaBpfEngine {
  + {static}PureJavaBpfEngine INSTANCE
  __
  +SeccompInstallationState getState$io_mazewall_enforcer()
  +boolean isSupported()
  +void install(Policy<?, ? extends Compiled>)
  +void installOnProcess(Policy<?, ? extends Compiled>)
}
interface "SeccompEngine" as io.mazewall.seccomp.SeccompEngine {
  + {abstract}void install(Policy<?, ? extends Compiled>)
  +void installOnProcess(Policy<?, ? extends Compiled>)
  + {abstract}boolean isSupported()
}
interface "SeccompInstallationState" as io.mazewall.seccomp.SeccompInstallationState {
}
class "SyscallInspection" as io.mazewall.seccomp.SyscallInspection {
  +int getSyscallNumber()
  +int getArgIndex()
  +ArgCheck getCheck()
  +SeccompAction getIfMatched()
  +SeccompAction getIfNotMatched()
}
io.mazewall.BpfFilter --> io.mazewall.BpfFilter
io.mazewall.LinuxNative .u.|> io.mazewall.NativeEngine
io.mazewall.LinuxNative .u.|> io.mazewall.NativeFileSystem
io.mazewall.LinuxNative .u.|> io.mazewall.NativeNetworking
io.mazewall.LinuxNative .u.|> io.mazewall.NativeProcess
io.mazewall.LinuxNative .u.|> io.mazewall.NativeMemory
io.mazewall.LinuxNative --> io.mazewall.NativeEngine
io.mazewall.LinuxNative --> io.mazewall.LinuxNative
io.mazewall.NativeEngine .u.|> io.mazewall.NativeFileSystem
io.mazewall.NativeEngine .u.|> io.mazewall.NativeNetworking
io.mazewall.NativeEngine .u.|> io.mazewall.NativeProcess
io.mazewall.NativeEngine .u.|> io.mazewall.NativeMemory
io.mazewall.Platform --> io.mazewall.Platform
io.mazewall.Policy --> io.mazewall.core.SandboxedPath
io.mazewall.Policy <--> io.mazewall.Policy
io.mazewall.Policy --> io.mazewall.seccomp.BpfInstruction
io.mazewall.Policy --> io.mazewall.core.SeccompAction
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeEngine
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeFileSystem
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeNetworking
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeProcess
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeMemory
io.mazewall.RealNativeEngine --> io.mazewall.RealNativeEngine
io.mazewall.SbobParser --> io.mazewall.SbobParser
io.mazewall.enforcer.ContainedExecutors --> io.mazewall.enforcer.ContainedExecutors
io.mazewall.enforcer.ContainerStateRegistry --> io.mazewall.enforcer.ContainerStateRegistry
io.mazewall.enforcer.ContainerStateRegistry --> io.mazewall.core.SeccompAction
io.mazewall.enforcer.ContainerStateRegistry --> io.mazewall.enforcer.ThreadLocalDelegate
io.mazewall.enforcer.ContainmentViolationDetector --> io.mazewall.enforcer.ContainmentViolationDetector
io.mazewall.enforcer.FilterInstallationPlanner --> io.mazewall.enforcer.FilterInstallationPlanner
io.mazewall.enforcer.JvmFloorWorkload --> io.mazewall.enforcer.JvmFloorWorkload
io.mazewall.enforcer.internal.ContainedExecutorWrapper --> io.mazewall.Policy
io.mazewall.ffi.LayoutValidator --> io.mazewall.ffi.LayoutValidator
io.mazewall.landlock.Landlock --> io.mazewall.landlock.Landlock
io.mazewall.landlock.LandlockSession --> io.mazewall.landlock.LandlockState
io.mazewall.landlock.LandlockSession --> io.mazewall.Policy
io.mazewall.seccomp.BpfProgram --> io.mazewall.seccomp.BpfInstruction
io.mazewall.seccomp.PureJavaBpfEngine .u.|> io.mazewall.seccomp.SeccompEngine
io.mazewall.seccomp.PureJavaBpfEngine --> io.mazewall.seccomp.SeccompInstallationState
io.mazewall.seccomp.PureJavaBpfEngine --> io.mazewall.seccomp.PureJavaBpfEngine
io.mazewall.seccomp.SyscallInspection --> io.mazewall.seccomp.ArgCheck
io.mazewall.seccomp.SyscallInspection --> io.mazewall.core.SeccompAction
@enduml
