@startuml Enforcer Class Diagram
!pragma useIntermediatePackages false
!theme spacelab
set separator none
hide empty members

class "BillOfBehaviorDto" as io.mazewall.BillOfBehaviorDto {
  + {static}Companion Companion
  __
  +Set<String> getOpens()
  +Set<String> getFsWritePaths()
  +Set<String> getSyscalls()
  +Set<String> getExecs()
  +List<StackProfileEntryDto> getStackProfile()
}
class "BpfFilter" as io.mazewall.BpfFilter {
  + {static}BpfFilter INSTANCE
  + {static}int SECCOMP_DATA_NR_OFFSET
  + {static}int SECCOMP_DATA_ARCH_OFFSET
  __
  +List<BpfInstruction> build(Arch, Policy<?, ?>, boolean)
  +void emitInspections(NrLoaded, List<SyscallInspection>, boolean, Set<Integer>)
}
class "LinuxNative" as io.mazewall.LinuxNative {
  + {static}LinuxNative INSTANCE
  __
  +void setEngine(NativeEngine)
  +void resetToDefault()
  +NativeTransaction getTRANSACTION_INSTANCE()
  +T withTransaction(Function1<? super NativeTransaction, ? extends T>)
  +NativeFileSystem getFileSystem()
  +NativeNetworking getNetworking()
  +NativeProcess getProcess()
  +NativeMemory getMemory()
  +SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor, long, MemorySegment)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor, long, long)
  +SyscallResult fcntl(NativeTransaction, FileDescriptor, int, long)
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
class "LinuxNativeKt" as io.mazewall.LinuxNativeKt {
  + {static}SyscallResult map(SyscallResult, Function1<? super T, ? extends R>)
  + {static}SyscallResult flatMap(SyscallResult, Function1<? super T, ? extends SyscallResult<? extends R, ? extends H>>)
  + {static}SyscallResult onSuccess(SyscallResult, Function1<? super T, Unit>)
  + {static}SyscallResult onFailure(SyscallResult, Function2<? super Integer, ? super Long, Unit>)
  + {static}T recover(SyscallResult, Function2<? super Integer, ? super Long, ? extends T>)
  + {static}int asInt(Success)
  + {static}FileDescriptor asFd(Success)
  + {static}int asInt(SyscallResult)
  + {static}FileDescriptor getFdOrThrow(SyscallResult, String)
}
interface "NativeEngine" as io.mazewall.NativeEngine {
  + {abstract}NativeFileSystem getFileSystem()
  + {abstract}NativeNetworking getNetworking()
  + {abstract}NativeProcess getProcess()
  + {abstract}NativeMemory getMemory()
  + {abstract}SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  + {abstract}SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  + {abstract}SyscallResult ioctl(NativeTransaction, FileDescriptor, long, MemorySegment)
  + {abstract}SyscallResult ioctl(NativeTransaction, FileDescriptor, long, long)
  + {abstract}SyscallResult fcntl(NativeTransaction, FileDescriptor, int, long)
  + {abstract}SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
interface "NativeFileSystem" as io.mazewall.NativeFileSystem {
  + {abstract}SyscallResult open(NativeTransaction, MemorySegment, int)
  + {abstract}SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
  + {abstract}SyscallResult close(FileDescriptor)
}
interface "NativeMemory" as io.mazewall.NativeMemory {
  + {abstract}SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  + {abstract}SyscallResult read(NativeTransaction, FileDescriptor, MemorySegment, long)
  + {abstract}SyscallResult write(NativeTransaction, FileDescriptor, MemorySegment, long)
  + {abstract}MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
interface "NativeNetworking" as io.mazewall.NativeNetworking {
  + {abstract}SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  + {abstract}SyscallResult socket(NativeTransaction, int, int, int)
  + {abstract}SyscallResult bind(NativeTransaction, FileDescriptor, MemorySegment, int)
  + {abstract}SyscallResult listen(NativeTransaction, FileDescriptor, int)
  + {abstract}SyscallResult accept(NativeTransaction, FileDescriptor, MemorySegment, MemorySegment)
  + {abstract}SyscallResult connect(NativeTransaction, FileDescriptor, MemorySegment, int)
  + {abstract}SyscallResult sendmsg(NativeTransaction, FileDescriptor, MemorySegment, int)
  + {abstract}SyscallResult recvmsg(NativeTransaction, FileDescriptor, MemorySegment, int)
  + {abstract}SyscallResult recv(NativeTransaction, FileDescriptor, MemorySegment, long, int)
}
interface "NativeProcess" as io.mazewall.NativeProcess {
  + {abstract}int gettid()
  + {abstract}SyscallResult prctl(NativeTransaction, int, NativeArg, NativeArg, NativeArg, NativeArg)
}
interface "NativeTransaction" as io.mazewall.NativeTransaction {
}
class "Platform" as io.mazewall.Platform {
  + {static}Platform INSTANCE
  __
  +boolean isLinux()
  +boolean isSupported()
  +boolean isArchitectureSupported()
  +FallbackBehavior configuredFallback()
  +String getYamaPath()
  +void setYamaPath(String)
  +Diagnostics diagnose()
}
class "Policy" as io.mazewall.Policy<S extends PolicyScope, State extends PolicyState> {
  + {static}Companion Companion
  + {static}Policy<ProcessWideSafe, Uncompiled> PURE_COMPUTE_UNSAFE
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_EXEC
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_NETWORK
  + {static}Policy<ThreadLocalOnly, Uncompiled> PURE_COMPUTE
  __
  +SeccompAction getDefaultAction()
  +Map<Syscall, SeccompAction> getSyscallActions()
  +boolean getAllowMmapExec()
  +boolean getAllowNonThreadClone()
  +boolean getAllowUnsafePrctl()
  +Set<SandboxedPath> getAllowedFsReadPaths()
  +Set<SandboxedPath> getAllowedFsWritePaths()
  +boolean getEnforceLandlock()
  +List<BpfInstruction> getCompiledFilters()
  +boolean isSyscallAllowed(Syscall)
  +Map<Integer, SeccompAction> syscallActionNumbers(Arch)
  + {static}Builder builder()
  + {static}Builder threadLocalBuilder()
}
class "PolicyKt" as io.mazewall.PolicyKt {
  + {static}Policy<S, Compiled> compile(Policy<? extends S, ? extends Uncompiled>, Arch)
  + {static}Policy<ProcessWideSafe, Uncompiled> plus(Policy<? extends ProcessWideSafe, ? extends Uncompiled>, Policy<? extends ProcessWideSafe, ? extends Uncompiled>)
  + {static}Policy<ThreadLocalOnly, Uncompiled> plusThreadLocal(Policy<?, ? extends Uncompiled>, Policy<? extends ThreadLocalOnly, ? extends Uncompiled>)
  + {static}Policy<ThreadLocalOnly, Uncompiled> plusThreadLocalReverse(Policy<? extends ThreadLocalOnly, ? extends Uncompiled>, Policy<? extends ProcessWideSafe, ? extends Uncompiled>)
}
interface "PolicyScope" as io.mazewall.PolicyScope {
}
interface "PolicyState" as io.mazewall.PolicyState {
}
class "RealNativeEngine" as io.mazewall.RealNativeEngine {
  + {static}RealNativeEngine INSTANCE
  __
  +NativeFileSystem getFileSystem()
  +NativeNetworking getNetworking()
  +NativeProcess getProcess()
  +NativeMemory getMemory()
  +SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor, long, MemorySegment)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor, long, long)
  +SyscallResult fcntl(NativeTransaction, FileDescriptor, int, long)
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
class "RealNativeFileSystem" as io.mazewall.RealNativeFileSystem {
  + {static}RealNativeFileSystem INSTANCE
  __
  +SyscallResult open(NativeTransaction, MemorySegment, int)
  +SyscallResult close(FileDescriptor)
  +SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
}
class "RealNativeHelper" as io.mazewall.RealNativeHelper {
  + {static}RealNativeHelper INSTANCE
  __
  +SyscallResult result(long, int)
  +MethodHandle downcall(String, FunctionDescriptor, Option[])
}
class "RealNativeMemory" as io.mazewall.RealNativeMemory {
  + {static}RealNativeMemory INSTANCE
  __
  +SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  +SyscallResult read(NativeTransaction, FileDescriptor, MemorySegment, long)
  +SyscallResult write(NativeTransaction, FileDescriptor, MemorySegment, long)
  +MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
class "RealNativeNetworking" as io.mazewall.RealNativeNetworking {
  + {static}RealNativeNetworking INSTANCE
  __
  +SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  +SyscallResult socket(NativeTransaction, int, int, int)
  +SyscallResult bind(NativeTransaction, FileDescriptor, MemorySegment, int)
  +SyscallResult listen(NativeTransaction, FileDescriptor, int)
  +SyscallResult accept(NativeTransaction, FileDescriptor, MemorySegment, MemorySegment)
  +SyscallResult connect(NativeTransaction, FileDescriptor, MemorySegment, int)
  +SyscallResult sendmsg(NativeTransaction, FileDescriptor, MemorySegment, int)
  +SyscallResult recvmsg(NativeTransaction, FileDescriptor, MemorySegment, int)
  +SyscallResult recv(NativeTransaction, FileDescriptor, MemorySegment, long, int)
}
class "RealNativeProcess" as io.mazewall.RealNativeProcess {
  + {static}RealNativeProcess INSTANCE
  __
  +int gettid()
  +SyscallResult prctl(NativeTransaction, int, NativeArg, NativeArg, NativeArg, NativeArg)
}
class "SbobParser" as io.mazewall.SbobParser {
  + {static}SbobParser INSTANCE
  __
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(Path, Policy<?, ? extends Uncompiled>, Path)
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(InputStream, Policy<?, ? extends Uncompiled>, Path)
  +Policy<ThreadLocalOnly, Uncompiled> parseJsonToPolicy(String, Policy<?, ? extends Uncompiled>, Path)
}
interface "SeccompMode" as io.mazewall.SeccompMode {
}
class "StackFrameDto" as io.mazewall.StackFrameDto {
  + {static}Companion Companion
  __
  +String getClassLoader()
  +String getModule()
  +String getModuleVersion()
  +String getClassName()
  +String getMethodName()
  +String getFileName()
  +int getLineNumber()
}
class "StackProfileEntryDto" as io.mazewall.StackProfileEntryDto {
  + {static}Companion Companion
  __
  +String getSyscall()
  +List<String> getPaths()
  +List<Long> getArgs()
  +List<StackFrameDto> getStackTrace()
}
interface "YamaPtraceScope" as io.mazewall.YamaPtraceScope {
}
class "Errno" as io.mazewall.core.Errno {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "FileDescriptor" as io.mazewall.core.FileDescriptor {
  +int getFd()
  +Arena getArena()
  +boolean isValid()
  +boolean isInvalid()
  +void close()
}
class "MemoryAddress" as io.mazewall.core.MemoryAddress {
  +long getValue()
  + {static}long toLong-impl(long)
  + {static}String toString-impl(long)
  + {static}int hashCode-impl(long)
  + {static}boolean equals-impl(long, Object)
  + {static}long constructor-impl(long)
  + {static}boolean equals-impl0(long, long)
}
interface "NativeArg" as io.mazewall.core.NativeArg {
  + {abstract}long getAsLong()
}
class "Pid" as io.mazewall.core.Pid {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "SandboxedPath" as io.mazewall.core.SandboxedPath {
  + {static}Companion Companion
  __
  +String getValue()
  + {static}String toString-impl(String)
  + {static}int hashCode-impl(String)
  + {static}boolean equals-impl(String, Object)
  + {static}boolean equals-impl0(String, String)
  + {static}String of(String, boolean)
}
enum "SeccompAction" as io.mazewall.core.SeccompAction {
  ACT_KILL_PROCESS
  ACT_KILL_THREAD
  ACT_TRAP
  ACT_ERRNO
  ACT_NOTIFY
  ACT_LOG
  ACT_ALLOW
  __
  +int getPriority()
  +int getNativeCode()
}
class "SyscallNumber" as io.mazewall.core.SyscallNumber {
  +int getNr()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "Uid" as io.mazewall.core.Uid {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "ContainedExecutors" as io.mazewall.enforcer.ContainedExecutors {
  ..
  + {static}ContainedExecutors INSTANCE
  __
  +void installOnCurrentThread(Policy<?, ? extends Uncompiled>[])
  +void installOnProcess(Policy<? extends ProcessWideSafe, ? extends Uncompiled>[])
  +ExecutorService wrap(ExecutorService, Policy<?, ? extends Uncompiled>[])
}
class "ContainmentViolationDetector" as io.mazewall.enforcer.ContainmentViolationDetector {
  + {static}ContainmentViolationDetector INSTANCE
  __
  +String[] getDENIED_PHRASES()
  +boolean isContainmentViolation(Throwable)
  +Throwable findViolationCause(Throwable)
}
class "ContainmentViolationException" as io.mazewall.enforcer.ContainmentViolationException {
}
class "FilterInstallationPlanner" as io.mazewall.enforcer.FilterInstallationPlanner {
  + {static}FilterInstallationPlanner INSTANCE
  __
  +FilterPlan calculateNewFilter(Policy<?, ? extends Uncompiled>, ContainerState)
  +void verifyFilterDepth(int)
}
class "JvmFloorWorkload" as io.mazewall.enforcer.JvmFloorWorkload {
  + {static}JvmFloorWorkload INSTANCE
  __
  +void run()
  + {static}void main(String[])
}
class "ProcessStateRegistry" as io.mazewall.enforcer.ProcessStateRegistry {
  + {static}ProcessStateRegistry INSTANCE
  __
  +AtomicReference<Map<Syscall, SeccompAction>> getSYSCALL_ACTIONS()
  +AtomicReference<SeccompAction> getDEFAULT_ACTION()
  +AtomicBoolean getALLOWS_MMAP_EXEC()
  +AtomicBoolean getALLOWS_NON_THREAD_CLONE()
  +AtomicBoolean getALLOWS_UNSAFE_PRCTL()
  +AtomicReference<Set<Syscall>> getALLOWED_SYSCALLS()
  +AtomicInteger getFILTER_DEPTH()
}
class "ThreadLocalDelegate" as io.mazewall.enforcer.ThreadLocalDelegate<T> {
  +T getValue(Object, KProperty<?>)
  +void setValue(Object, KProperty<?>, T)
}
class "ThreadLocalDelegateKt" as io.mazewall.enforcer.ThreadLocalDelegateKt {
  + {static}ThreadLocalDelegate<T> threadLocal(Function0<? extends T>)
}
class "ThreadStateRegistry" as io.mazewall.enforcer.ThreadStateRegistry {
  + {static}ThreadStateRegistry INSTANCE
  __
  +Map<Syscall, SeccompAction> getSyscallActions()
  +void setSyscallActions(Map<Syscall, ? extends SeccompAction>)
  +SeccompAction getDefaultAction()
  +void setDefaultAction(SeccompAction)
  +boolean getAllowsMmapExec()
  +void setAllowsMmapExec(boolean)
  +boolean getAllowsNonThreadClone()
  +void setAllowsNonThreadClone(boolean)
  +boolean getAllowsUnsafePrctl()
  +void setAllowsUnsafePrctl(boolean)
  +Set<Syscall> getAllowedSyscalls()
  +void setAllowedSyscalls(Set<? extends Syscall>)
  +int getFilterDepth()
  +void setFilterDepth(int)
  +Set<SandboxedPath> getLandlockAppliedReads()
  +void setLandlockAppliedReads(Set<SandboxedPath>)
  +Set<SandboxedPath> getLandlockAppliedWrites()
  +void setLandlockAppliedWrites(Set<SandboxedPath>)
  +void sanitize()
}
class "ValidationKt" as io.mazewall.enforcer.ValidationKt {
  + {static}void validateLinuxAndNotVirtual()
}
class "ContainedExecutorWrapper" as io.mazewall.enforcer.internal.ContainedExecutorWrapper {
  +void execute(Runnable)
  +Future<T> submit(Callable<T>)
  +Future<T> submit(Runnable, T)
  +Future<?> submit(Runnable)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>, long, TimeUnit)
  +T invokeAny(Collection<? extends Callable<T>>)
  +T invokeAny(Collection<? extends Callable<T>>, long, TimeUnit)
  +void close()
  +void shutdown()
  +List<Runnable> shutdownNow()
  +boolean isShutdown()
  +boolean isTerminated()
  +boolean awaitTermination(long, TimeUnit)
}
class "LayoutValidator" as io.mazewall.ffi.LayoutValidator {
  + {static}LayoutValidator INSTANCE
  __
  +void validate()
}
class "ConfinedSegment" as io.mazewall.ffi.memory.ConfinedSegment {
  +MemorySegment getSegment()
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "ErrnoSegment" as io.mazewall.ffi.memory.ErrnoSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}int getErrno-impl(MemorySegment)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "LandlockPathBeneathAttrSegment" as io.mazewall.ffi.memory.LandlockPathBeneathAttrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getAllowedAccess-impl(MemorySegment)
  + {static}void setAllowedAccess-impl(MemorySegment, long)
  + {static}int getParentFd-impl(MemorySegment)
  + {static}void setParentFd-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "LandlockRulesetAttrSegment" as io.mazewall.ffi.memory.LandlockRulesetAttrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getHandledAccessFs-impl(MemorySegment)
  + {static}void setHandledAccessFs-impl(MemorySegment, long)
  + {static}long getHandledAccessNet-impl(MemorySegment)
  + {static}void setHandledAccessNet-impl(MemorySegment, long)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
interface "ManagedSegment" as io.mazewall.ffi.memory.ManagedSegment {
  + {abstract}MemorySegment getSegment()
}
class "NativeScopeKt" as io.mazewall.ffi.memory.NativeScopeKt {
  + {static}T nativeScope(Function1<? super Arena, ? extends T>)
}
class "PollFdSegment" as io.mazewall.ffi.memory.PollFdSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}int getFd-impl(MemorySegment)
  + {static}void setFd-impl(MemorySegment, int)
  + {static}short getEvents-impl(MemorySegment)
  + {static}void setEvents-impl(MemorySegment, short)
  + {static}short getRevents-impl(MemorySegment)
  + {static}void setRevents-impl(MemorySegment, short)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SharedSegment" as io.mazewall.ffi.memory.SharedSegment {
  +MemorySegment getSegment()
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SockFilterSegment" as io.mazewall.ffi.memory.SockFilterSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}short getCode-impl(MemorySegment)
  + {static}void setCode-impl(MemorySegment, short)
  + {static}byte getJt-impl(MemorySegment)
  + {static}void setJt-impl(MemorySegment, byte)
  + {static}byte getJf-impl(MemorySegment)
  + {static}void setJf-impl(MemorySegment, byte)
  + {static}int getK-impl(MemorySegment)
  + {static}void setK-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SockFprogSegment" as io.mazewall.ffi.memory.SockFprogSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}short getLen-impl(MemorySegment)
  + {static}void setLen-impl(MemorySegment, short)
  + {static}MemorySegment getFilter-impl(MemorySegment)
  + {static}void setFilter-impl(MemorySegment, MemorySegment)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "Landlock" as io.mazewall.landlock.Landlock {
  + {static}Landlock INSTANCE
  + {static}long LANDLOCK_ACCESS_FS_EXECUTE
  + {static}long LANDLOCK_ACCESS_FS_WRITE_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_FILE
  + {static}long LANDLOCK_ACCESS_FS_MAKE_CHAR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_DIR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_REG
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_FIFO
  + {static}long LANDLOCK_ACCESS_FS_MAKE_BLOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SYM
  + {static}long LANDLOCK_ACCESS_FS_REFER
  + {static}long LANDLOCK_ACCESS_FS_TRUNCATE
  + {static}long LANDLOCK_ACCESS_FS_IOCTL_DEV
  __
  +void applyRestrictiveBarrier()
  +boolean isSupported()
  +int getAbiVersion()
  +void applyRuleset(Policy<?, ? extends Uncompiled>)
  +long getFullAccessMask(int)
  +void handleUnsupportedLandlock()
  +void addJvmClasspathRules(Arena, FileDescriptor, long)
  +void enforceRuleset(FileDescriptor)
  +void applyUserRules(Arena, FileDescriptor, Policy<?, ?>, int, long)
  +long getAccessMask(int, Policy<?, ?>)
  +SyscallResult createRuleset(Arena, long, int)
}
interface "LandlockLifecycle" as io.mazewall.landlock.LandlockLifecycle {
}
class "LandlockSession" as io.mazewall.landlock.LandlockSession {
  +LandlockState getState()
  +void applyRuleset()
}
interface "LandlockState" as io.mazewall.landlock.LandlockState {
}
interface "ArgCheck" as io.mazewall.seccomp.ArgCheck {
}
abstract class "BpfBuilder" as io.mazewall.seccomp.BpfBuilder {
  +List<BpfMacro> getOps()
}
abstract class "BpfInstruction" as io.mazewall.seccomp.BpfInstruction {
  + {static}Companion Companion
  __
  + {abstract}short getCode()
  + {abstract}short getJt()
  + {abstract}short getJf()
  + {abstract}int getK()
}
interface "BpfMacro" as io.mazewall.seccomp.BpfMacro {
}
class "BpfProgram" as io.mazewall.seccomp.BpfProgram {
  + {static}Companion Companion
  __
  +List<BpfInstruction> getInstructions()
  + {static}Uninitialized builder()
  + {static}BpfProgram dsl(Arch, Consumer<NrLoaded>)
}
class "PureJavaBpfEngine" as io.mazewall.seccomp.PureJavaBpfEngine {
  + {static}PureJavaBpfEngine INSTANCE
  __
  +SeccompInstallationState getState()
  +boolean isSupported()
  +void install(Policy<?, ? extends Compiled>)
  +void installOnProcess(Policy<?, ? extends Compiled>)
  +void setNoNewPrivs()
  +FilterApplied installFilter(Arch, MemorySegment, boolean)
  +void verifyInstallation(Policy<?, ?>)
}
interface "SeccompEngine" as io.mazewall.seccomp.SeccompEngine {
  + {abstract}void install(Policy<?, ? extends Compiled>)
  +void installOnProcess(Policy<?, ? extends Compiled>)
  + {abstract}boolean isSupported()
}
interface "SeccompInstallationState" as io.mazewall.seccomp.SeccompInstallationState {
}
class "SyscallInspection" as io.mazewall.seccomp.SyscallInspection {
  +int getSyscallNumber()
  +int getArgIndex()
  +ArgCheck getCheck()
  +SeccompAction getIfMatched()
  +SeccompAction getIfNotMatched()
}
io.mazewall.BillOfBehaviorDto --> io.mazewall.StackProfileEntryDto
io.mazewall.BpfFilter --> io.mazewall.BpfFilter
io.mazewall.LinuxNative .u.|> io.mazewall.NativeEngine
io.mazewall.LinuxNative --> io.mazewall.NativeEngine
io.mazewall.LinuxNative --> io.mazewall.LinuxNative
io.mazewall.Platform --> io.mazewall.Platform
io.mazewall.Policy --> io.mazewall.core.SandboxedPath
io.mazewall.Policy <--> io.mazewall.Policy
io.mazewall.Policy --> io.mazewall.seccomp.BpfInstruction
io.mazewall.Policy --> io.mazewall.core.SeccompAction
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeEngine
io.mazewall.RealNativeEngine --> io.mazewall.NativeProcess
io.mazewall.RealNativeEngine --> io.mazewall.NativeNetworking
io.mazewall.RealNativeEngine --> io.mazewall.NativeMemory
io.mazewall.RealNativeEngine --> io.mazewall.RealNativeEngine
io.mazewall.RealNativeEngine --> io.mazewall.NativeFileSystem
io.mazewall.RealNativeFileSystem .u.|> io.mazewall.NativeFileSystem
io.mazewall.RealNativeFileSystem --> io.mazewall.RealNativeFileSystem
io.mazewall.RealNativeHelper --> io.mazewall.RealNativeHelper
io.mazewall.RealNativeMemory .u.|> io.mazewall.NativeMemory
io.mazewall.RealNativeMemory --> io.mazewall.RealNativeMemory
io.mazewall.RealNativeNetworking .u.|> io.mazewall.NativeNetworking
io.mazewall.RealNativeNetworking --> io.mazewall.RealNativeNetworking
io.mazewall.RealNativeProcess .u.|> io.mazewall.NativeProcess
io.mazewall.RealNativeProcess --> io.mazewall.RealNativeProcess
io.mazewall.SbobParser --> io.mazewall.SbobParser
io.mazewall.StackProfileEntryDto --> io.mazewall.StackFrameDto
io.mazewall.enforcer.ContainedExecutors --> io.mazewall.enforcer.ContainedExecutors
io.mazewall.enforcer.ContainmentViolationDetector --> io.mazewall.enforcer.ContainmentViolationDetector
io.mazewall.enforcer.FilterInstallationPlanner --> io.mazewall.enforcer.FilterInstallationPlanner
io.mazewall.enforcer.JvmFloorWorkload --> io.mazewall.enforcer.JvmFloorWorkload
io.mazewall.enforcer.ProcessStateRegistry --> io.mazewall.enforcer.ProcessStateRegistry
io.mazewall.enforcer.ProcessStateRegistry --> io.mazewall.core.SeccompAction
io.mazewall.enforcer.ThreadStateRegistry --> io.mazewall.enforcer.ThreadLocalDelegate
io.mazewall.enforcer.ThreadStateRegistry --> io.mazewall.enforcer.ThreadStateRegistry
io.mazewall.enforcer.internal.ContainedExecutorWrapper --> io.mazewall.Policy
io.mazewall.ffi.LayoutValidator --> io.mazewall.ffi.LayoutValidator
io.mazewall.ffi.memory.ConfinedSegment .u.|> io.mazewall.ffi.memory.ManagedSegment
io.mazewall.ffi.memory.SharedSegment .u.|> io.mazewall.ffi.memory.ManagedSegment
io.mazewall.landlock.Landlock --> io.mazewall.landlock.Landlock
io.mazewall.landlock.LandlockSession --> io.mazewall.landlock.LandlockState
io.mazewall.landlock.LandlockSession --> io.mazewall.Policy
io.mazewall.seccomp.BpfBuilder --> io.mazewall.seccomp.BpfMacro
io.mazewall.seccomp.BpfProgram --> io.mazewall.seccomp.BpfInstruction
io.mazewall.seccomp.PureJavaBpfEngine .u.|> io.mazewall.seccomp.SeccompEngine
io.mazewall.seccomp.PureJavaBpfEngine --> io.mazewall.seccomp.SeccompInstallationState
io.mazewall.seccomp.PureJavaBpfEngine --> io.mazewall.seccomp.PureJavaBpfEngine
io.mazewall.seccomp.SyscallInspection --> io.mazewall.seccomp.ArgCheck
io.mazewall.seccomp.SyscallInspection --> io.mazewall.core.SeccompAction
@enduml
