@startuml Enforcer Class Diagram
!pragma useIntermediatePackages false
!theme spacelab
set separator none
hide empty members

class "BillOfBehaviorDto" as io.mazewall.BillOfBehaviorDto {
  + {static}Companion Companion
  __
  +Set<String> getOpens()
  +Set<String> getFsWritePaths()
  +Set<String> getSyscalls()
  +Set<String> getExecs()
  +List<StackProfileEntryDto> getStackProfile()
}
class "BpfFilter" as io.mazewall.BpfFilter {
  + {static}BpfFilter INSTANCE
  + {static}int SECCOMP_DATA_NR_OFFSET
  + {static}int SECCOMP_DATA_ARCH_OFFSET
  __
  +List<BpfInstruction> build(Arch, PolicyDefinition<?>, boolean)
  +SyscallInspectionPipeline getSyscallInspectionPipeline()
  +void emitInspections(NrLoaded, List<SyscallInspection>, boolean, Set<Integer>)
}
class "CompiledSandbox" as io.mazewall.CompiledSandbox<S extends PolicyScope> {
  +PolicyDefinition<S> getDefinition()
  +List<BpfInstruction> getCompiledFilters()
}
class "KernelFeatureMatrix" as io.mazewall.KernelFeatureMatrix {
  + {static}Companion Companion
  __
  +boolean getSeccompSupported()
  +boolean getSeccompTsyncSupported()
  +boolean getSeccompUserNotifSupported()
  +int getLandlockAbiVersion()
  +boolean getLandlockTsyncSupported()
  +boolean getLandlockSupported()
}
class "LinuxNative" as io.mazewall.LinuxNative {
  + {static}LinuxNative INSTANCE
  __
  +void setEngine(NativeEngine)
  +void resetToDefault()
  +void setTransactionManager(TransactionManager)
  +void resetTransactionManager()
  +T withTransaction(Function1<? super NativeTransaction, ? extends T>)
  +NativeFileSystem getFileSystem()
  +NativeNetworking getNetworking()
  +NativeProcess getProcess()
  +NativeMemory getMemory()
  +SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, MemorySegment)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, long)
  +SyscallResult fcntl(NativeTransaction, FileDescriptor<?, ? extends Open>, int, long)
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
class "LinuxNativeKt" as io.mazewall.LinuxNativeKt {
  + {static}boolean isSuccess(SyscallResult)
  + {static}boolean isFailure(SyscallResult)
  + {static}SyscallResult map(SyscallResult, Function1<? super T, ? extends R>)
  + {static}SyscallResult flatMap(SyscallResult, Function1<? super T, ? extends SyscallResult<? extends R, ? extends H>>)
  + {static}SyscallResult onSuccess(SyscallResult, Function1<? super T, Unit>)
  + {static}SyscallResult onFailure(SyscallResult, Function2<? super Integer, ? super Long, Unit>)
  + {static}T recover(SyscallResult, Function2<? super Integer, ? super Long, ? extends T>)
  + {static}long asLong(Success)
  + {static}FileDescriptor<Generic, Open> asFd(Success)
  + {static}int asInt(SyscallResult)
  + {static}FileDescriptor<Generic, Open> getFdOrThrow(SyscallResult, String)
}
interface "NativeEngine" as io.mazewall.NativeEngine {
  + {abstract}NativeFileSystem getFileSystem()
  + {abstract}NativeNetworking getNetworking()
  + {abstract}NativeProcess getProcess()
  + {abstract}NativeMemory getMemory()
  + {abstract}SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  + {abstract}SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  + {abstract}SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, MemorySegment)
  + {abstract}SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, long)
  + {abstract}SyscallResult fcntl(NativeTransaction, FileDescriptor<?, ? extends Open>, int, long)
  + {abstract}SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
interface "NativeFileSystem" as io.mazewall.NativeFileSystem {
  + {abstract}SyscallResult open(NativeTransaction, MemorySegment, int)
  + {abstract}SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
  + {abstract}SyscallResult mmap(NativeTransaction, long, long, int, int, int, long)
  + {abstract}SyscallResult close(FileDescriptor<?, ? extends Open>)
}
interface "NativeMemory" as io.mazewall.NativeMemory {
  + {abstract}SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  + {abstract}SyscallResult read(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}SyscallResult write(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
interface "NativeNetworking" as io.mazewall.NativeNetworking {
  + {abstract}SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  + {abstract}SyscallResult socket(NativeTransaction, int, int, int)
  + {abstract}SyscallResult bind(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  + {abstract}SyscallResult listen(NativeTransaction, FileDescriptor<?, ? extends Open>, int)
  + {abstract}SyscallResult accept(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, MemorySegment)
  + {abstract}SyscallResult connect(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  + {abstract}SyscallResult sendmsg(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  + {abstract}SyscallResult recvmsg(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  + {abstract}SyscallResult recv(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
}
interface "NativeProcess" as io.mazewall.NativeProcess {
  + {abstract}int gettid()
  + {abstract}SyscallResult prctl(NativeTransaction, PrctlCommand)
}
interface "NativeTransaction" as io.mazewall.NativeTransaction {
}
class "Platform" as io.mazewall.Platform {
  + {static}Platform INSTANCE
  __
  +KernelFeatureMatrix getFeatureMatrix()
  +void setProvider(PlatformProvider)
  +void resetToDefault()
  +boolean isLinux()
  +boolean isSupported()
  +boolean isArchitectureSupported()
  +FallbackBehavior configuredFallback()
  +Diagnostics diagnose()
}
interface "PlatformProvider" as io.mazewall.PlatformProvider {
  + {abstract}String getOsName()
  + {abstract}String getOsVersion()
  + {abstract}String getOsArch()
  + {abstract}boolean hasKernelSeccompSupport()
  + {abstract}SeccompMode getSeccompMode()
  + {abstract}SyscallResult checkSeccompSanity()
  + {abstract}boolean isNoNewPrivsEnabled()
  + {abstract}YamaPtraceScope getYamaPtraceScope()
  + {abstract}int getLandlockAbiVersion()
  + {abstract}boolean probeSeccompTsync()
  + {abstract}boolean probeSeccompUserNotif()
  + {abstract}boolean isContainer()
}
class "Policy" as io.mazewall.Policy<S extends PolicyScope, State extends PolicyState> {
  + {static}Companion Companion
  + {static}Policy<ProcessWideSafe, Uncompiled> PURE_COMPUTE_UNSAFE
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_EXEC
  + {static}Policy<ProcessWideSafe, Uncompiled> NO_NETWORK
  + {static}Policy<ThreadLocalOnly, Uncompiled> PURE_COMPUTE
  __
  +PolicyDefinition<S> getDefinition()
  +SeccompAction getDefaultAction()
  +Map<Syscall, SeccompAction> getSyscallActions()
  +boolean getAllowMmapExec()
  +boolean getAllowNonThreadClone()
  +boolean getAllowUnsafePrctl()
  +Set<SandboxedPath> getAllowedFsReadPaths()
  +Set<SandboxedPath> getAllowedFsWritePaths()
  +boolean getEnforceLandlock()
  +List<BpfInstruction> getCompiledFilters()
  +boolean isSyscallAllowed(Syscall)
  +Map<Integer, SeccompAction> syscallActionNumbers(Arch)
  +SyscallInspectionPipeline getSyscallInspectionPipeline()
  + {static}Builder builder()
  + {static}Builder threadLocalBuilder()
}
class "PolicyBuilder" as io.mazewall.PolicyBuilder<S extends PolicyScope> {
  +PolicyBuilder<S> defaultAction(SeccompAction)
  +PolicyBuilder<S> addAction(SeccompAction, Syscall[])
  +PolicyBuilder<S> block(Syscall[])
  +PolicyBuilder<S> allow(Syscall[])
  +PolicyBuilder<S> supervise(Syscall[])
  +PolicyBuilder<S> unblock(Syscall[])
  +PolicyBuilder<S> base(PolicyDefinition<? extends S>)
  +PolicyBuilder<ThreadLocalOnly> allowFsRead(String)
  +PolicyBuilder<ThreadLocalOnly> allowFsRead(String)
  +PolicyBuilder<ThreadLocalOnly> allowJvmClasspath()
  +PolicyBuilder<ThreadLocalOnly> allowFsWrite(String)
  +PolicyBuilder<ThreadLocalOnly> allowFsWrite(String)
  +PolicyBuilder<S> allowMmapExec()
  +PolicyBuilder<S> allowNonThreadClone()
  +PolicyBuilder<S> allowUnsafePrctl()
  +PolicyDefinition<S> build()
}
class "PolicyDefinition" as io.mazewall.PolicyDefinition<S extends PolicyScope> {
  + {static}Companion Companion
  __
  +SeccompAction getDefaultAction()
  +Map<Syscall, SeccompAction> getSyscallActions()
  +boolean getAllowMmapExec()
  +boolean getAllowNonThreadClone()
  +boolean getAllowUnsafePrctl()
  +Set<SandboxedPath> getAllowedFsReadPaths()
  +Set<SandboxedPath> getAllowedFsWritePaths()
  +boolean getEnforceLandlock()
  +boolean getHasSupervisedSyscalls()
  +boolean isSyscallAllowed(Syscall)
  +Map<Integer, SeccompAction> syscallActionNumbers(Arch)
}
class "PolicyDefinitionKt" as io.mazewall.PolicyDefinitionKt {
  + {static}CompiledSandbox<S> compile(PolicyDefinition<? extends S>, Arch)
}
class "PolicyKt" as io.mazewall.PolicyKt {
  + {static}Policy<S, Compiled> compile(Policy<? extends S, ? extends Uncompiled>, Arch)
  + {static}Policy<ProcessWideSafe, Uncompiled> plusProcessWide(Policy<? extends ProcessWideSafe, ? extends Uncompiled>, Policy<? extends ProcessWideSafe, ? extends Uncompiled>)
  + {static}Policy<ThreadLocalOnly, Uncompiled> plusThreadLocal(Policy<? extends S, ? extends Uncompiled>, Policy<? extends ThreadLocalOnly, ? extends Uncompiled>)
}
class "PolicyPresets" as io.mazewall.PolicyPresets {
  + {static}PolicyPresets INSTANCE
  + {static}PolicyDefinition<ProcessWideSafe> PURE_COMPUTE_UNSAFE
  + {static}PolicyDefinition<ProcessWideSafe> NO_EXEC
  + {static}PolicyDefinition<ProcessWideSafe> NO_NETWORK
  + {static}PolicyDefinition<ThreadLocalOnly> PURE_COMPUTE
}
interface "PolicyScope" as io.mazewall.PolicyScope {
}
interface "PolicyState" as io.mazewall.PolicyState {
}
class "RealNativeEngine" as io.mazewall.RealNativeEngine {
  + {static}RealNativeEngine INSTANCE
  __
  +NativeFileSystem getFileSystem()
  +NativeNetworking getNetworking()
  +NativeProcess getProcess()
  +NativeMemory getMemory()
  +SyscallResult syscall(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult syscall4(NativeTransaction, long, NativeArg, NativeArg, NativeArg, NativeArg)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, MemorySegment)
  +SyscallResult ioctl(NativeTransaction, FileDescriptor<?, ? extends Open>, long, long)
  +SyscallResult fcntl(NativeTransaction, FileDescriptor<?, ? extends Open>, int, long)
  +SyscallResult poll(NativeTransaction, MemorySegment, long, int)
}
class "RealNativeFileSystem" as io.mazewall.RealNativeFileSystem {
  + {static}RealNativeFileSystem INSTANCE
  __
  +SyscallResult open(NativeTransaction, MemorySegment, int)
  +SyscallResult mmap(NativeTransaction, long, long, int, int, int, long)
  +SyscallResult close(FileDescriptor<?, ? extends Open>)
  +SyscallResult readlink(NativeTransaction, MemorySegment, MemorySegment, long)
}
class "RealNativeHelper" as io.mazewall.RealNativeHelper {
  + {static}RealNativeHelper INSTANCE
  __
  +SyscallResult result(long, int)
  +MethodHandle downcall(String, FunctionDescriptor, Option[])
}
class "RealNativeMemory" as io.mazewall.RealNativeMemory {
  + {static}RealNativeMemory INSTANCE
  __
  +SyscallResult processVmReadv(NativeTransaction, int, MemorySegment, long, MemorySegment, long, long)
  +SyscallResult read(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +SyscallResult write(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +MemorySegment newSockFProg(Arena, List<? extends BpfInstruction>)
}
class "RealNativeNetworking" as io.mazewall.RealNativeNetworking {
  + {static}RealNativeNetworking INSTANCE
  __
  +SyscallResult socketpair(NativeTransaction, int, int, int, MemorySegment)
  +SyscallResult socket(NativeTransaction, int, int, int)
  +SyscallResult bind(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  +SyscallResult listen(NativeTransaction, FileDescriptor<?, ? extends Open>, int)
  +SyscallResult accept(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, MemorySegment)
  +SyscallResult connect(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  +SyscallResult sendmsg(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  +SyscallResult recvmsg(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, int)
  +SyscallResult recv(NativeTransaction, FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
}
class "RealNativeProcess" as io.mazewall.RealNativeProcess {
  + {static}RealNativeProcess INSTANCE
  __
  +int gettid()
  +SyscallResult prctl(NativeTransaction, PrctlCommand)
}
class "RealPlatformProvider" as io.mazewall.RealPlatformProvider {
  + {static}RealPlatformProvider INSTANCE
  + {static}String yamaPath
  __
  +String getOsName()
  +String getOsVersion()
  +String getOsArch()
  +boolean hasKernelSeccompSupport()
  +SeccompMode getSeccompMode()
  +SyscallResult checkSeccompSanity()
  +boolean isNoNewPrivsEnabled()
  +YamaPtraceScope getYamaPtraceScope()
  +int getLandlockAbiVersion()
  +boolean probeSeccompTsync()
  +boolean probeSeccompUserNotif()
  +boolean isContainer()
}
class "RealTransactionManager" as io.mazewall.RealTransactionManager {
  + {static}RealTransactionManager INSTANCE
  __
  +NativeTransaction getTRANSACTION_INSTANCE()
  +T withTransaction(Function1<? super NativeTransaction, ? extends T>)
}
class "SbobParser" as io.mazewall.SbobParser {
  + {static}SbobParser INSTANCE
  __
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(Path, Policy<?, ? extends Uncompiled>, Path)
  +Policy<ThreadLocalOnly, Uncompiled> parseToPolicy(InputStream, Policy<?, ? extends Uncompiled>, Path)
  +Policy<ThreadLocalOnly, Uncompiled> parseJsonToPolicy(String, Policy<?, ? extends Uncompiled>, Path)
}
interface "SeccompMode" as io.mazewall.SeccompMode {
}
class "StackFrameDto" as io.mazewall.StackFrameDto {
  + {static}Companion Companion
  __
  +String getClassLoader()
  +String getModule()
  +String getModuleVersion()
  +String getClassName()
  +String getMethodName()
  +String getFileName()
  +int getLineNumber()
}
class "StackProfileEntryDto" as io.mazewall.StackProfileEntryDto {
  + {static}Companion Companion
  __
  +String getSyscall()
  +List<String> getPaths()
  +List<Long> getArgs()
  +List<StackFrameDto> getStackTrace()
}
interface "TransactionManager" as io.mazewall.TransactionManager {
  + {abstract}T withTransaction(Function1<? super NativeTransaction, ? extends T>)
}
class "UnsupportedKernelFeatureException" as io.mazewall.UnsupportedKernelFeatureException {
}
interface "YamaPtraceScope" as io.mazewall.YamaPtraceScope {
}
class "Errno" as io.mazewall.core.Errno {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
interface "FdState" as io.mazewall.core.FdState {
}
class "FileDescriptor" as io.mazewall.core.FileDescriptor<R extends FileDescriptorRole, S extends FdState> {
  + {static}Companion Companion
  __
  +int getValue()
  +Arena getArena()
  +boolean isValid()
  +boolean isInvalid()
  +void close()
  +FileDescriptor<R, Closed> closeFd()
}
interface "FileDescriptorRole" as io.mazewall.core.FileDescriptorRole {
}
class "MemoryAddress" as io.mazewall.core.MemoryAddress {
  +long getValue()
  + {static}long toLong-impl(long)
  + {static}String toString-impl(long)
  + {static}int hashCode-impl(long)
  + {static}boolean equals-impl(long, Object)
  + {static}long constructor-impl(long)
  + {static}boolean equals-impl0(long, long)
}
interface "NativeArg" as io.mazewall.core.NativeArg {
  + {abstract}long getAsLong()
}
class "Pid" as io.mazewall.core.Pid {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
abstract class "PrctlCommand" as io.mazewall.core.PrctlCommand {
  +int getOption()
  + {abstract}NativeArg getArg2()
  + {abstract}NativeArg getArg3()
  + {abstract}NativeArg getArg4()
  + {abstract}NativeArg getArg5()
}
class "SandboxedPath" as io.mazewall.core.SandboxedPath {
  + {static}Companion Companion
  __
  +String getValue()
  + {static}String toString-impl(String)
  + {static}int hashCode-impl(String)
  + {static}boolean equals-impl(String, Object)
  + {static}boolean equals-impl0(String, String)
  + {static}String of(String, boolean)
}
enum "SeccompAction" as io.mazewall.core.SeccompAction {
  ACT_KILL_PROCESS
  ACT_KILL_THREAD
  ACT_TRAP
  ACT_ERRNO
  ACT_NOTIFY
  ACT_LOG
  ACT_ALLOW
  __
  +int getPriority()
  +int getNativeCode()
}
class "SyscallNumber" as io.mazewall.core.SyscallNumber {
  +int getNr()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "Tid" as io.mazewall.core.Tid {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "Uid" as io.mazewall.core.Uid {
  +int getValue()
  + {static}String toString-impl(int)
  + {static}int hashCode-impl(int)
  + {static}boolean equals-impl(int, Object)
  + {static}int constructor-impl(int)
  + {static}boolean equals-impl0(int, int)
}
class "ContainedExecutors" as io.mazewall.enforcer.ContainedExecutors {
  ..
  + {static}ContainedExecutors INSTANCE
  __
  +void installOnCurrentThread(Policy<?, ? extends Uncompiled>[])
  +void installOnCurrentThread(Policy<?, ? extends Uncompiled>, StacktraceScopingPolicy)
  +AutoCloseable installOnCurrentThread(PolicyDefinition<?>)
  +AutoCloseable installOnCurrentThread(PolicyDefinition<?>, StacktraceScopingPolicy)
  +void installOnProcess(Policy<? extends ProcessWideSafe, ? extends Uncompiled>[])
  +ExecutorService wrap(ExecutorService, Policy<?, ? extends Uncompiled>[])
  +ExecutorService wrap(ExecutorService, Policy<?, ? extends Uncompiled>, StacktraceScopingPolicy)
}
class "ContainerState" as io.mazewall.enforcer.ContainerState {
  +int getFilterDepth()
  +Set<Syscall> getAllowedSyscalls()
  +SeccompAction getDefaultAction()
  +Map<Syscall, SeccompAction> getSyscallActions()
  +Set<SandboxedPath> getLandlockAppliedReads()
  +Set<SandboxedPath> getLandlockAppliedWrites()
  +SeccompInstallationState getEngineState()
  +boolean getAllowsMmapExec()
  +boolean getAllowsNonThreadClone()
  +boolean getAllowsUnsafePrctl()
  +ContainerState withNewSeccompPolicy(PolicyDefinition<?>, Map<Syscall, ? extends SeccompAction>, SeccompAction)
  +ContainerState withLandlockPaths(Set<SandboxedPath>, Set<SandboxedPath>)
  +ContainerState withEngineState(SeccompInstallationState)
}
class "ContainmentViolationDetector" as io.mazewall.enforcer.ContainmentViolationDetector {
  + {static}ContainmentViolationDetector INSTANCE
  __
  +String[] getDENIED_PHRASES()
  +void registerMatcher(ViolationMatcher)
  +void resetToDefaults()
  +boolean isContainmentViolation(Throwable)
  +Throwable findViolationCause(Throwable)
}
class "ContainmentViolationException" as io.mazewall.enforcer.ContainmentViolationException {
}
class "FilterInstallationPlanner" as io.mazewall.enforcer.FilterInstallationPlanner {
  + {static}FilterInstallationPlanner INSTANCE
  __
  +FilterPlan calculateNewFilter(PolicyDefinition<?>, ContainerState)
  +void verifyFilterDepth(int)
}
class "JvmFloorWorkload" as io.mazewall.enforcer.JvmFloorWorkload {
  + {static}JvmFloorWorkload INSTANCE
  __
  +void run()
  + {static}void main(String[])
}
class "ProcessStateRegistry" as io.mazewall.enforcer.ProcessStateRegistry {
  + {static}ProcessStateRegistry INSTANCE
  __
  +ContainerState getState()
  +void setState(ContainerState)
  +void update(Function1<? super ContainerState, ContainerState>)
}
class "SandboxDispatcher" as io.mazewall.enforcer.SandboxDispatcher {
  + {static}SandboxDispatcher INSTANCE
  __
  + {static}T execute(Policy<?, ?>, Callable<T>)
  +T executeBlock(Policy<?, ?>, Function0<? extends T>)
  +ExecutorService getOrCreateElasticPool(PolicyDefinition<?>)
  + {static}void shutdownAll()
}
class "SandboxDispatcherCoroutinesKt" as io.mazewall.enforcer.SandboxDispatcherCoroutinesKt {
  + {static}Object executeSuspend(SandboxDispatcher, Policy<?, ?>, Function1<? super Continuation<? super T>, ? extends Object>, Continuation<? super T>)
  + {static}CoroutineDispatcher asDispatcher(Policy<?, ?>)
}
class "ThreadLocalDelegate" as io.mazewall.enforcer.ThreadLocalDelegate<T> {
  +T getValue(Object, KProperty<?>)
  +void setValue(Object, KProperty<?>, T)
}
class "ThreadLocalDelegateKt" as io.mazewall.enforcer.ThreadLocalDelegateKt {
  + {static}ThreadLocalDelegate<T> threadLocal(Function0<? extends T>)
}
class "ThreadStateRegistry" as io.mazewall.enforcer.ThreadStateRegistry {
  + {static}ThreadStateRegistry INSTANCE
  __
  +ContainerState getState()
  +void setState(ContainerState)
  +void sanitize()
}
class "ValidationKt" as io.mazewall.enforcer.ValidationKt {
  + {static}void validateLinuxAndNotVirtual()
}
interface "ViolationMatcher" as io.mazewall.enforcer.ViolationMatcher {
  + {abstract}boolean matches(Throwable)
}
class "ContainedExecutorWrapper" as io.mazewall.enforcer.internal.ContainedExecutorWrapper {
  +void execute(Runnable)
  +Future<T> submit(Callable<T>)
  +Future<T> submit(Runnable, T)
  +Future<?> submit(Runnable)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>)
  +List<Future<T>> invokeAll(Collection<? extends Callable<T>>, long, TimeUnit)
  +T invokeAny(Collection<? extends Callable<T>>)
  +T invokeAny(Collection<? extends Callable<T>>, long, TimeUnit)
  +void close()
  +void shutdown()
  +List<Runnable> shutdownNow()
  +boolean isShutdown()
  +boolean isTerminated()
  +boolean awaitTermination(long, TimeUnit)
}
class "DefaultStacktraceScopingPolicy" as io.mazewall.enforcer.supervisor.DefaultStacktraceScopingPolicy {
  + {static}DefaultStacktraceScopingPolicy INSTANCE
  __
  +boolean authorize(int, Syscall, List<? extends Object>, List<StackTraceElement>)
}
class "JVMValidationListener" as io.mazewall.enforcer.supervisor.JVMValidationListener {
  + {static}Companion Companion
  __
  +void start(CountDownLatch)
}
class "JvmStackInspector" as io.mazewall.enforcer.supervisor.JvmStackInspector {
  + {static}JvmStackInspector INSTANCE
  __
  +ScopingValidationState inspect(int, List<? extends Object>, Thread)
}
abstract class "LoopAction" as io.mazewall.enforcer.supervisor.LoopAction {
}
interface "ScopingValidationState" as io.mazewall.enforcer.supervisor.ScopingValidationState {
}
interface "StacktraceScopingPolicy" as io.mazewall.enforcer.supervisor.StacktraceScopingPolicy {
  + {abstract}boolean authorize(int, Syscall, List<? extends Object>, List<StackTraceElement>)
}
class "SupervisorContext" as io.mazewall.enforcer.supervisor.SupervisorContext {
  +String getSocketPath()
  +Path getSocketDir()
  +Process getDaemonProcess()
  +Thread getShutdownHook()
}
class "SupervisorDaemon" as io.mazewall.enforcer.supervisor.SupervisorDaemon {
  + {static}SupervisorDaemon INSTANCE
  + {static}String DAEMON_READY_SENTINEL
  __
  + {static}void main(String[])
}
class "SupervisorDaemonEngine" as io.mazewall.enforcer.supervisor.SupervisorDaemonEngine {
  + {static}Companion Companion
  __
  +SupervisorDaemonState getState()
  +void run()
  +void triggerGlobalShutdown(String)
}
class "SupervisorDaemonManager" as io.mazewall.enforcer.supervisor.SupervisorDaemonManager {
  + {static}SupervisorDaemonManager INSTANCE
  __
  +SupervisorContext getOrSpawnSharedDaemon()
  +void stop()
}
interface "SupervisorDaemonState" as io.mazewall.enforcer.supervisor.SupervisorDaemonState {
}
class "SupervisorInstaller" as io.mazewall.enforcer.supervisor.SupervisorInstaller {
  + {static}SupervisorInstaller INSTANCE
  __
  +ConcurrentHashMap<Tid, Thread> getThreadRegistry()
  +void registerThread(int)
  +void unregisterThread(int)
  +SupervisorSession installSupervisedFilterForThread(PolicyDefinition<?>, StacktraceScopingPolicy)
}
class "SupervisorSession" as io.mazewall.enforcer.supervisor.SupervisorSession {
  +void close()
}
class "SupervisorSessionHandler" as io.mazewall.enforcer.supervisor.SupervisorSessionHandler {
  + {static}Companion Companion
  __
  +LoopAction handleActiveListener(MemorySegment, MemorySegment, MemorySegment)
}
class "SupervisorSocketInputStream" as io.mazewall.enforcer.supervisor.SupervisorSocketInputStream {
  + {static}Companion Companion
  __
  +int read()
  +int read(byte[], int, int)
  +void close()
}
class "SyscallArguments" as io.mazewall.enforcer.supervisor.SyscallArguments {
  +String getPathStr()
  +byte[] getSockaddrBytes()
}
class "LayoutValidator" as io.mazewall.ffi.LayoutValidator {
  + {static}LayoutValidator INSTANCE
  __
  +void validate()
}
class "CmsghdrSegment" as io.mazewall.ffi.memory.CmsghdrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getCmsgLen-impl(MemorySegment)
  + {static}void setCmsgLen-impl(MemorySegment, long)
  + {static}int getCmsgLevel-impl(MemorySegment)
  + {static}void setCmsgLevel-impl(MemorySegment, int)
  + {static}int getCmsgType-impl(MemorySegment)
  + {static}void setCmsgType-impl(MemorySegment, int)
  + {static}int getDataFd-impl(MemorySegment)
  + {static}void setDataFd-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "ConfinedSegment" as io.mazewall.ffi.memory.ConfinedSegment {
  +MemorySegment getSegment()
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "ErrnoSegment" as io.mazewall.ffi.memory.ErrnoSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}int getErrno-impl(MemorySegment)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "IovecSegment" as io.mazewall.ffi.memory.IovecSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}MemorySegment getIovBase-impl(MemorySegment)
  + {static}void setIovBase-impl(MemorySegment, MemorySegment)
  + {static}long getIovLen-impl(MemorySegment)
  + {static}void setIovLen-impl(MemorySegment, long)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "LandlockPathBeneathAttrSegment" as io.mazewall.ffi.memory.LandlockPathBeneathAttrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getAllowedAccess-impl(MemorySegment)
  + {static}void setAllowedAccess-impl(MemorySegment, long)
  + {static}int getParentFd-impl(MemorySegment)
  + {static}void setParentFd-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "LandlockRulesetAttrSegment" as io.mazewall.ffi.memory.LandlockRulesetAttrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getHandledAccessFs-impl(MemorySegment)
  + {static}void setHandledAccessFs-impl(MemorySegment, long)
  + {static}long getHandledAccessNet-impl(MemorySegment)
  + {static}void setHandledAccessNet-impl(MemorySegment, long)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
interface "ManagedSegment" as io.mazewall.ffi.memory.ManagedSegment {
  + {abstract}MemorySegment getSegment()
}
class "MemoryWrappersKt" as io.mazewall.ffi.memory.MemoryWrappersKt {
  + {static}byte readByte(MemorySegment, long)
  + {static}void writeByte(MemorySegment, long, byte)
  + {static}short readShort(MemorySegment, long)
  + {static}void writeShort(MemorySegment, long, short)
  + {static}int readInt(MemorySegment, long)
  + {static}void writeInt(MemorySegment, long, int)
  + {static}int readIntUnaligned(MemorySegment, long)
  + {static}void writeIntUnaligned(MemorySegment, long, int)
  + {static}long readLong(MemorySegment, long)
  + {static}void writeLong(MemorySegment, long, long)
  + {static}long readLongUnaligned(MemorySegment, long)
  + {static}void writeLongUnaligned(MemorySegment, long, long)
  + {static}MemorySegment readAddress(MemorySegment, long)
  + {static}void writeAddress(MemorySegment, long, MemorySegment)
  + {static}void writeIntBigEndian(MemorySegment, long, int)
  + {static}void writeIntBigEndianUnaligned(MemorySegment, long, int)
  + {static}void writeLongBigEndian(MemorySegment, long, long)
  + {static}void writeLongBigEndianUnaligned(MemorySegment, long, long)
}
class "MsghdrSegment" as io.mazewall.ffi.memory.MsghdrSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}MemorySegment getMsgName-impl(MemorySegment)
  + {static}void setMsgName-impl(MemorySegment, MemorySegment)
  + {static}int getMsgNamelen-impl(MemorySegment)
  + {static}void setMsgNamelen-impl(MemorySegment, int)
  + {static}MemorySegment getMsgIov-impl(MemorySegment)
  + {static}void setMsgIov-impl(MemorySegment, MemorySegment)
  + {static}long getMsgIovlen-impl(MemorySegment)
  + {static}void setMsgIovlen-impl(MemorySegment, long)
  + {static}MemorySegment getMsgControl-impl(MemorySegment)
  + {static}void setMsgControl-impl(MemorySegment, MemorySegment)
  + {static}long getMsgControllen-impl(MemorySegment)
  + {static}void setMsgControllen-impl(MemorySegment, long)
  + {static}int getMsgFlags-impl(MemorySegment)
  + {static}void setMsgFlags-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "NativeScopeKt" as io.mazewall.ffi.memory.NativeScopeKt {
  + {static}T nativeScope(Function1<? super Arena, ? extends T>)
}
class "PollFdSegment" as io.mazewall.ffi.memory.PollFdSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}int getFd-impl(MemorySegment)
  + {static}void setFd-impl(MemorySegment, int)
  + {static}short getEvents-impl(MemorySegment)
  + {static}void setEvents-impl(MemorySegment, short)
  + {static}short getRevents-impl(MemorySegment)
  + {static}void setRevents-impl(MemorySegment, short)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SeccompNotifAddFdSegment" as io.mazewall.ffi.memory.SeccompNotifAddFdSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getId-impl(MemorySegment)
  + {static}void setId-impl(MemorySegment, long)
  + {static}int getFlags-impl(MemorySegment)
  + {static}void setFlags-impl(MemorySegment, int)
  + {static}int getSrcfd-impl(MemorySegment)
  + {static}void setSrcfd-impl(MemorySegment, int)
  + {static}int getNewfd-impl(MemorySegment)
  + {static}void setNewfd-impl(MemorySegment, int)
  + {static}int getNewfdFlags-impl(MemorySegment)
  + {static}void setNewfdFlags-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SharedSegment" as io.mazewall.ffi.memory.SharedSegment {
  +MemorySegment getSegment()
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SockFilterSegment" as io.mazewall.ffi.memory.SockFilterSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}short getCode-impl(MemorySegment)
  + {static}void setCode-impl(MemorySegment, short)
  + {static}byte getJt-impl(MemorySegment)
  + {static}void setJt-impl(MemorySegment, byte)
  + {static}byte getJf-impl(MemorySegment)
  + {static}void setJf-impl(MemorySegment, byte)
  + {static}int getK-impl(MemorySegment)
  + {static}void setK-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SockFprogSegment" as io.mazewall.ffi.memory.SockFprogSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}short getLen-impl(MemorySegment)
  + {static}void setLen-impl(MemorySegment, short)
  + {static}MemorySegment getFilter-impl(MemorySegment)
  + {static}void setFilter-impl(MemorySegment, MemorySegment)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SockaddrUnSegment" as io.mazewall.ffi.memory.SockaddrUnSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}short getSunFamily-impl(MemorySegment)
  + {static}void setSunFamily-impl(MemorySegment, short)
  + {static}MemorySegment getSunPath-impl(MemorySegment)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "SupervisorProcessMemoryReader" as io.mazewall.ffi.memory.SupervisorProcessMemoryReader {
  + {static}SupervisorProcessMemoryReader INSTANCE
  __
  +String readString(int, long, int, boolean)
  +byte[] readBytes(int, long, int, boolean)
}
class "SupervisorResponseSegment" as io.mazewall.ffi.memory.SupervisorResponseSegment {
  + {static}Companion Companion
  __
  +MemorySegment getSegment()
  + {static}long getId-impl(MemorySegment)
  + {static}void setId-impl(MemorySegment, long)
  + {static}byte getDecision-impl(MemorySegment)
  + {static}void setDecision-impl(MemorySegment, byte)
  + {static}int getErrorNr-impl(MemorySegment)
  + {static}void setErrorNr-impl(MemorySegment, int)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
class "NetworkOrderBuffer" as io.mazewall.ffi.networking.NetworkOrderBuffer {
  +MemorySegment getSegment()
  + {static}void writeInt-impl(MemorySegment, long, int)
  + {static}void writeIntUnaligned-impl(MemorySegment, long, int)
  + {static}void writeLong-impl(MemorySegment, long, long)
  + {static}void writeLongUnaligned-impl(MemorySegment, long, long)
  + {static}void writeByte-impl(MemorySegment, long, byte)
  + {static}String toString-impl(MemorySegment)
  + {static}int hashCode-impl(MemorySegment)
  + {static}boolean equals-impl(MemorySegment, Object)
  + {static}MemorySegment constructor-impl(MemorySegment)
  + {static}boolean equals-impl0(MemorySegment, MemorySegment)
}
abstract class "SeccompConnection" as io.mazewall.ffi.networking.SeccompConnection {
  + {abstract}FileDescriptor<UnixSocket, Open> getSocketFd()
}
class "SupervisorSeccompNotifInstaller" as io.mazewall.ffi.networking.SupervisorSeccompNotifInstaller {
  + {static}SupervisorSeccompNotifInstaller INSTANCE
  __
  +void install(String, List<? extends BpfInstruction>, boolean, Function1<? super String, Integer>, Function2<? super Integer, ? super Integer, Boolean>, Function2<? super Integer, ? super CountDownLatch, Unit>)
}
class "SupervisorSocketUtils" as io.mazewall.ffi.networking.SupervisorSocketUtils {
  + {static}SupervisorSocketUtils INSTANCE
  + {static}int AF_UNIX
  + {static}int SOCK_STREAM
  + {static}int BACKLOG_SIZE
  + {static}int SOCKADDR_UN_SIZE
  + {static}long CMSG_RIGHTS_LEN
  + {static}long MSG_CONTROL_BUF_SIZE
  + {static}int SOL_SOCKET
  + {static}int SCM_RIGHTS
  __
  +MemorySegment setupSockAddrUn(Arena, String)
  +int connectWithRetry(String, int, long)
  +boolean sendDescriptor(int, int)
  +FileDescriptor<SeccompNotif, Open> recvDescriptor(FileDescriptor<UnixSocket, ? extends Open>)
}
class "Landlock" as io.mazewall.landlock.Landlock {
  + {static}Landlock INSTANCE
  + {static}long LANDLOCK_ACCESS_FS_EXECUTE
  + {static}long LANDLOCK_ACCESS_FS_WRITE_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_FILE
  + {static}long LANDLOCK_ACCESS_FS_READ_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_DIR
  + {static}long LANDLOCK_ACCESS_FS_REMOVE_FILE
  + {static}long LANDLOCK_ACCESS_FS_MAKE_CHAR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_DIR
  + {static}long LANDLOCK_ACCESS_FS_MAKE_REG
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_FIFO
  + {static}long LANDLOCK_ACCESS_FS_MAKE_BLOCK
  + {static}long LANDLOCK_ACCESS_FS_MAKE_SYM
  + {static}long LANDLOCK_ACCESS_FS_REFER
  + {static}long LANDLOCK_ACCESS_FS_TRUNCATE
  + {static}long LANDLOCK_ACCESS_FS_IOCTL_DEV
  __
  +void applyRestrictiveBarrier()
  +boolean isSupported()
  +int getAbiVersion()
  +void applyRuleset(PolicyDefinition<?>, boolean)
  +long getFullAccessMask(int)
  +void handleUnsupportedLandlock()
  +void addJvmClasspathRules(Arena, LandlockRuleset<? extends Building>, long)
  +LandlockRuleset<Sealed> enforceRuleset(LandlockRuleset<? extends Building>, boolean)
  +void applyUserRules(Arena, LandlockRuleset<? extends Building>, PolicyDefinition<?>, int, long)
  +long getAccessMask(int, PolicyDefinition<?>)
  +SyscallResult createRuleset(Arena, long, int)
}
interface "LandlockLifecycle" as io.mazewall.landlock.LandlockLifecycle {
}
class "LandlockRuleset" as io.mazewall.landlock.LandlockRuleset<S extends RulesetState> {
  +FileDescriptor<Ruleset, Open> getFd()
}
class "LandlockSession" as io.mazewall.landlock.LandlockSession {
  +LandlockState getState()
  +void applyRuleset()
}
interface "LandlockState" as io.mazewall.landlock.LandlockState {
}
interface "RulesetState" as io.mazewall.landlock.RulesetState {
}
class "BobDeserializer" as io.mazewall.sbob.BobDeserializer {
  + {static}BobDeserializer INSTANCE
  __
  +BillOfBehaviorDto deserialize(String)
}
class "PathNormalizer" as io.mazewall.sbob.PathNormalizer {
  + {static}PathNormalizer INSTANCE
  __
  +Set<String> normalizeAndPrune(Set<String>, Path)
}
class "PolicyTransformer" as io.mazewall.sbob.PolicyTransformer {
  + {static}PolicyTransformer INSTANCE
  __
  +PolicyDefinition<ThreadLocalOnly> transform(BillOfBehaviorDto, Set<String>, Set<String>, PolicyDefinition<?>)
}
interface "ArgCheck" as io.mazewall.seccomp.ArgCheck {
}
abstract class "BpfBuilder" as io.mazewall.seccomp.BpfBuilder {
  +List<BpfMacro> getOps()
  +AtomicInteger getLabelCounter()
  +String nextLabel(String)
}
abstract class "BpfInstruction" as io.mazewall.seccomp.BpfInstruction {
  + {static}Companion Companion
  __
  + {abstract}short getCode()
  + {abstract}short getJt()
  + {abstract}short getJf()
  + {abstract}int getK()
}
interface "BpfMacro" as io.mazewall.seccomp.BpfMacro {
}
class "BpfProgram" as io.mazewall.seccomp.BpfProgram {
  + {static}Companion Companion
  __
  +List<BpfInstruction> getInstructions()
  + {static}Uninitialized builder()
  + {static}BpfProgram dsl(Arch, Function<NrLoaded, Terminated>)
}
class "Clone3Inspector" as io.mazewall.seccomp.Clone3Inspector {
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
}
class "DefaultSyscallInspectionPipeline" as io.mazewall.seccomp.DefaultSyscallInspectionPipeline {
  +List<SyscallInspector> getInspectors()
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
interface "EngineState" as io.mazewall.seccomp.EngineState {
}
class "InspectionContext" as io.mazewall.seccomp.InspectionContext {
  +Map<Integer, SeccompAction> getSyscallActions()
  +SeccompAction getDefaultAction()
  +Set<Integer> getJvmCriticalNrs()
  +boolean getAllowMmapExec()
  +boolean getAllowNonThreadClone()
  +boolean getAllowUnsafePrctl()
  +SeccompAction resolveEffectiveAction(int)
}
class "MmapExecInspector" as io.mazewall.seccomp.MmapExecInspector {
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
class "PureJavaBpfEngine" as io.mazewall.seccomp.PureJavaBpfEngine {
  + {static}PureJavaBpfEngine INSTANCE
  __
  +EngineState getState()
  +boolean isSupported()
  +SeccompEngine<Loaded> install(CompiledSandbox<?>)
  +SeccompEngine<Loaded> installOnProcess(CompiledSandbox<?>)
  +void setNoNewPrivs()
  +FilterApplied installFilter(Arch, MemorySegment, boolean)
  +void verifyInstallation(PolicyDefinition<?>)
}
interface "SeccompEngine" as io.mazewall.seccomp.SeccompEngine<S extends EngineState> {
  + {abstract}S getState()
  + {abstract}SeccompEngine<Loaded> install(CompiledSandbox<?>)
  +SeccompEngine<Loaded> installOnProcess(CompiledSandbox<?>)
  + {abstract}boolean isSupported()
}
interface "SeccompInstallationState" as io.mazewall.seccomp.SeccompInstallationState {
}
class "SyscallInspection" as io.mazewall.seccomp.SyscallInspection {
  +int getSyscallNumber()
  +int getArgIndex()
  +ArgCheck getCheck()
  +SeccompAction getIfMatched()
  +SeccompAction getIfNotMatched()
}
interface "SyscallInspectionPipeline" as io.mazewall.seccomp.SyscallInspectionPipeline {
  + {abstract}List<SyscallInspector> getInspectors()
  + {abstract}List<SyscallInspection> getInspections(Arch, InspectionContext)
  + {abstract}void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
interface "SyscallInspector" as io.mazewall.seccomp.SyscallInspector {
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
class "ThreadCloneInspector" as io.mazewall.seccomp.ThreadCloneInspector {
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
class "UnsafePrctlInspector" as io.mazewall.seccomp.UnsafePrctlInspector {
  +List<SyscallInspection> getInspections(Arch, InspectionContext)
  +void emitSpecial(NrLoaded, Arch, InspectionContext, Set<Integer>)
}
io.mazewall.BillOfBehaviorDto --> io.mazewall.StackProfileEntryDto
io.mazewall.BpfFilter --> io.mazewall.BpfFilter
io.mazewall.CompiledSandbox --> io.mazewall.PolicyDefinition
io.mazewall.CompiledSandbox --> io.mazewall.seccomp.BpfInstruction
io.mazewall.LinuxNative .u.|> io.mazewall.NativeEngine
io.mazewall.LinuxNative --> io.mazewall.NativeEngine
io.mazewall.LinuxNative --> io.mazewall.LinuxNative
io.mazewall.LinuxNative --> io.mazewall.TransactionManager
io.mazewall.Platform --> io.mazewall.PlatformProvider
io.mazewall.Platform --> io.mazewall.Platform
io.mazewall.Platform --> io.mazewall.KernelFeatureMatrix
io.mazewall.Policy --> io.mazewall.PolicyDefinition
io.mazewall.Policy <--> io.mazewall.Policy
io.mazewall.Policy --> io.mazewall.seccomp.BpfInstruction
io.mazewall.PolicyBuilder --> io.mazewall.core.SandboxedPath
io.mazewall.PolicyBuilder --> io.mazewall.core.SeccompAction
io.mazewall.PolicyDefinition --> io.mazewall.core.SandboxedPath
io.mazewall.PolicyDefinition --> io.mazewall.core.SeccompAction
io.mazewall.PolicyPresets --> io.mazewall.PolicyDefinition
io.mazewall.PolicyPresets --> io.mazewall.PolicyPresets
io.mazewall.RealNativeEngine .u.|> io.mazewall.NativeEngine
io.mazewall.RealNativeEngine --> io.mazewall.NativeProcess
io.mazewall.RealNativeEngine --> io.mazewall.NativeNetworking
io.mazewall.RealNativeEngine --> io.mazewall.NativeMemory
io.mazewall.RealNativeEngine --> io.mazewall.RealNativeEngine
io.mazewall.RealNativeEngine --> io.mazewall.NativeFileSystem
io.mazewall.RealNativeFileSystem .u.|> io.mazewall.NativeFileSystem
io.mazewall.RealNativeFileSystem --> io.mazewall.RealNativeFileSystem
io.mazewall.RealNativeHelper --> io.mazewall.RealNativeHelper
io.mazewall.RealNativeMemory .u.|> io.mazewall.NativeMemory
io.mazewall.RealNativeMemory --> io.mazewall.RealNativeMemory
io.mazewall.RealNativeNetworking .u.|> io.mazewall.NativeNetworking
io.mazewall.RealNativeNetworking --> io.mazewall.RealNativeNetworking
io.mazewall.RealNativeProcess .u.|> io.mazewall.NativeProcess
io.mazewall.RealNativeProcess --> io.mazewall.RealNativeProcess
io.mazewall.RealPlatformProvider .u.|> io.mazewall.PlatformProvider
io.mazewall.RealPlatformProvider --> io.mazewall.RealPlatformProvider
io.mazewall.RealTransactionManager .u.|> io.mazewall.TransactionManager
io.mazewall.RealTransactionManager --> io.mazewall.RealTransactionManager
io.mazewall.SbobParser --> io.mazewall.SbobParser
io.mazewall.StackProfileEntryDto --> io.mazewall.StackFrameDto
io.mazewall.core.FileDescriptor --> io.mazewall.core.FileDescriptor
io.mazewall.enforcer.ContainedExecutors --> io.mazewall.enforcer.ContainedExecutors
io.mazewall.enforcer.ContainerState --> io.mazewall.seccomp.SeccompInstallationState
io.mazewall.enforcer.ContainerState --> io.mazewall.core.SandboxedPath
io.mazewall.enforcer.ContainerState --> io.mazewall.core.SeccompAction
io.mazewall.enforcer.ContainmentViolationDetector --> io.mazewall.enforcer.ViolationMatcher
io.mazewall.enforcer.ContainmentViolationDetector --> io.mazewall.enforcer.ContainmentViolationDetector
io.mazewall.enforcer.FilterInstallationPlanner --> io.mazewall.enforcer.FilterInstallationPlanner
io.mazewall.enforcer.JvmFloorWorkload --> io.mazewall.enforcer.JvmFloorWorkload
io.mazewall.enforcer.ProcessStateRegistry --> io.mazewall.enforcer.ProcessStateRegistry
io.mazewall.enforcer.ProcessStateRegistry --> io.mazewall.enforcer.ContainerState
io.mazewall.enforcer.SandboxDispatcher --> io.mazewall.enforcer.SandboxDispatcher
io.mazewall.enforcer.SandboxDispatcher --> io.mazewall.PolicyDefinition
io.mazewall.enforcer.ThreadStateRegistry --> io.mazewall.enforcer.ThreadLocalDelegate
io.mazewall.enforcer.ThreadStateRegistry --> io.mazewall.enforcer.ThreadStateRegistry
io.mazewall.enforcer.internal.ContainedExecutorWrapper --> io.mazewall.enforcer.supervisor.StacktraceScopingPolicy
io.mazewall.enforcer.internal.ContainedExecutorWrapper --> io.mazewall.PolicyDefinition
io.mazewall.enforcer.supervisor.DefaultStacktraceScopingPolicy .u.|> io.mazewall.enforcer.supervisor.StacktraceScopingPolicy
io.mazewall.enforcer.supervisor.DefaultStacktraceScopingPolicy --> io.mazewall.enforcer.supervisor.DefaultStacktraceScopingPolicy
io.mazewall.enforcer.supervisor.JVMValidationListener --> io.mazewall.core.FileDescriptor
io.mazewall.enforcer.supervisor.JVMValidationListener --> io.mazewall.enforcer.supervisor.StacktraceScopingPolicy
io.mazewall.enforcer.supervisor.JvmStackInspector --> io.mazewall.enforcer.supervisor.JvmStackInspector
io.mazewall.enforcer.supervisor.SupervisorDaemon --> io.mazewall.enforcer.supervisor.SupervisorDaemon
io.mazewall.enforcer.supervisor.SupervisorDaemonEngine --> io.mazewall.core.FileDescriptor
io.mazewall.enforcer.supervisor.SupervisorDaemonEngine --> io.mazewall.enforcer.supervisor.SupervisorDaemonState
io.mazewall.enforcer.supervisor.SupervisorDaemonManager --> io.mazewall.enforcer.supervisor.SupervisorContext
io.mazewall.enforcer.supervisor.SupervisorDaemonManager --> io.mazewall.enforcer.supervisor.SupervisorDaemonManager
io.mazewall.enforcer.supervisor.SupervisorInstaller --> io.mazewall.enforcer.supervisor.SupervisorInstaller
io.mazewall.enforcer.supervisor.SupervisorInstaller --> io.mazewall.core.Tid
io.mazewall.enforcer.supervisor.SupervisorSessionHandler --> io.mazewall.core.FileDescriptor
io.mazewall.enforcer.supervisor.SupervisorSocketInputStream --> io.mazewall.core.FileDescriptor
io.mazewall.ffi.LayoutValidator --> io.mazewall.ffi.LayoutValidator
io.mazewall.ffi.memory.ConfinedSegment .u.|> io.mazewall.ffi.memory.ManagedSegment
io.mazewall.ffi.memory.SharedSegment .u.|> io.mazewall.ffi.memory.ManagedSegment
io.mazewall.ffi.memory.SupervisorProcessMemoryReader --> io.mazewall.ffi.memory.SupervisorProcessMemoryReader
io.mazewall.ffi.networking.SupervisorSeccompNotifInstaller --> io.mazewall.ffi.networking.SupervisorSeccompNotifInstaller
io.mazewall.ffi.networking.SupervisorSocketUtils --> io.mazewall.ffi.networking.SupervisorSocketUtils
io.mazewall.landlock.Landlock --> io.mazewall.landlock.Landlock
io.mazewall.landlock.LandlockRuleset --> io.mazewall.core.FileDescriptor
io.mazewall.landlock.LandlockSession --> io.mazewall.landlock.LandlockState
io.mazewall.landlock.LandlockSession --> io.mazewall.PolicyDefinition
io.mazewall.sbob.BobDeserializer --> io.mazewall.sbob.BobDeserializer
io.mazewall.sbob.PathNormalizer --> io.mazewall.sbob.PathNormalizer
io.mazewall.sbob.PolicyTransformer --> io.mazewall.sbob.PolicyTransformer
io.mazewall.seccomp.BpfBuilder --> io.mazewall.seccomp.BpfMacro
io.mazewall.seccomp.BpfProgram --> io.mazewall.seccomp.BpfInstruction
io.mazewall.seccomp.Clone3Inspector .u.|> io.mazewall.seccomp.SyscallInspector
io.mazewall.seccomp.DefaultSyscallInspectionPipeline .u.|> io.mazewall.seccomp.SyscallInspectionPipeline
io.mazewall.seccomp.DefaultSyscallInspectionPipeline --> io.mazewall.seccomp.SyscallInspector
io.mazewall.seccomp.InspectionContext --> io.mazewall.core.SeccompAction
io.mazewall.seccomp.MmapExecInspector .u.|> io.mazewall.seccomp.SyscallInspector
io.mazewall.seccomp.PureJavaBpfEngine .u.|> io.mazewall.seccomp.SeccompEngine
io.mazewall.seccomp.PureJavaBpfEngine --> io.mazewall.seccomp.PureJavaBpfEngine
io.mazewall.seccomp.SyscallInspection --> io.mazewall.seccomp.ArgCheck
io.mazewall.seccomp.SyscallInspection --> io.mazewall.core.SeccompAction
io.mazewall.seccomp.ThreadCloneInspector .u.|> io.mazewall.seccomp.SyscallInspector
io.mazewall.seccomp.UnsafePrctlInspector .u.|> io.mazewall.seccomp.SyscallInspector
@enduml
