@startuml Profiler Class Diagram
!pragma useIntermediatePackages false
!theme spacelab
set separator none
hide empty members

class "BaselinePathProfile" as io.mazewall.profiler.BaselinePathProfile {
  +Set<String> getExactPaths()
  +Set<String> getPathPrefixes()
  +boolean matches(String)
}
class "BillOfBehavior" as io.mazewall.profiler.BillOfBehavior {
  + {static}Companion Companion
  __
  +Set<String> getOpens()
  +Set<String> getFsWritePaths()
  +Set<Syscall> getSyscalls()
  +Set<String> getExecs()
  +Map<TraceEvent, List<StackTraceElement[]>> getStackProfile()
  +BillOfBehavior plus(BillOfBehavior)
  +BillOfBehavior filterPaths(BaselinePathProfile)
  +String toJson()
  +String toStackTracesJson()
}
class "BillOfBehaviorKt" as io.mazewall.profiler.BillOfBehaviorKt {
}
class "JvmBaselineProfiles" as io.mazewall.profiler.JvmBaselineProfiles {
  + {static}JvmBaselineProfiles INSTANCE
  __
  +BaselinePathProfile jvmBootstrapNoise()
}
class "Profiler" as io.mazewall.profiler.Profiler {
  + {static}Profiler INSTANCE
  __
  +ConcurrentHashMap<Tid, Thread> getThreadRegistry()
  +void shutdown()
}
class "ProfilingResult" as io.mazewall.profiler.ProfilingResult<T> {
  +T getValue()
  +BillOfBehavior getBehavior()
  +Map<TraceEvent, List<StackTraceElement[]>> getStackProfile()
}
interface "TraceableWorkload" as io.mazewall.profiler.TraceableWorkload {
}
class "BobCompiler" as io.mazewall.profiler.compiler.BobCompiler {
  + {static}BobCompiler INSTANCE
  __
  +BillOfBehavior compile(List<? extends TraceEvent>)
}
abstract class "HandshakeSession" as io.mazewall.profiler.engine.HandshakeSession {
  + {abstract}long getNotifId()
  + {abstract}FileDescriptor<SeccompNotif, Open> getListenerFd()
}
abstract class "LoopAction" as io.mazewall.profiler.engine.LoopAction {
}
interface "NativeIoOperations" as io.mazewall.profiler.engine.NativeIoOperations {
  + {abstract}SyscallResult poll(MemorySegment, long, int)
  + {abstract}SyscallResult read(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}SyscallResult write(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}SyscallResult recv(FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
  + {abstract}SyscallResult ioctl(FileDescriptor<?, ? extends Open>, long, MemorySegment)
}
class "ProfilerDaemon" as io.mazewall.profiler.engine.ProfilerDaemon {
  + {static}ProfilerDaemon INSTANCE
  __
  + {static}void main(String[])
}
class "ProfilerDaemonEngine" as io.mazewall.profiler.engine.ProfilerDaemonEngine {
  + {static}Companion Companion
  __
  +ProfilerDaemonState getState()
  +void run()
  +void triggerGlobalShutdown(String)
}
interface "ProfilerDaemonState" as io.mazewall.profiler.engine.ProfilerDaemonState {
}
class "ProfilerInstaller" as io.mazewall.profiler.engine.ProfilerInstaller {
  + {static}ProfilerInstaller INSTANCE
  __
  +void installProfilingFilterForThread(String, PolicyDefinition<?>, List<TraceEvent>, Map<TraceEvent, List<StackTraceElement[]>>, Map<String, Long>, Function0<? extends Thread>, boolean, Function1<? super String, Integer>, Function6<? super Integer, ? super List<TraceEvent>, ? super Map<TraceEvent, List<StackTraceElement[]>>, ? super Map<String, Long>, ? super Function0<? extends Thread>, ? super CountDownLatch, Unit>)
}
class "ProfilerInstallerSession" as io.mazewall.profiler.engine.ProfilerInstallerSession {
  +void install()
}
interface "ProfilerInstallerState" as io.mazewall.profiler.engine.ProfilerInstallerState {
}
interface "ProfilerMemoryReader" as io.mazewall.profiler.engine.ProfilerMemoryReader {
  + {abstract}String readStringFromProcess(int, long, int)
  + {abstract}String resolveLink(int, String)
}
class "ProfilerSessionHandler" as io.mazewall.profiler.engine.ProfilerSessionHandler {
  + {static}Companion Companion
  __
  +SessionEventLedger getLedger()
  +ProfilerState getState()
  +LoopAction handleActiveListener(MemorySegment, MemorySegment, MemorySegment, MemorySegment, MemorySegment)
  +boolean processNotification(MemorySegment, MemorySegment, MemorySegment, MemorySegment)
}
interface "ProfilerState" as io.mazewall.profiler.engine.ProfilerState {
  + {abstract}FileDescriptor<UnixSocket, Open> getSocketFd()
  + {abstract}FileDescriptor<SeccompNotif, Open> getListenerFd()
}
interface "ProfilerTransport" as io.mazewall.profiler.engine.ProfilerTransport {
}
class "RealMemoryReader" as io.mazewall.profiler.engine.RealMemoryReader {
  + {static}RealMemoryReader INSTANCE
  __
  +String readStringFromProcess(int, long, int)
  +String resolveLink(int, String)
}
class "RealProfilerTransport" as io.mazewall.profiler.engine.RealProfilerTransport {
  + {static}RealProfilerTransport INSTANCE
  __
  +void sendTraceEvent(FileDescriptor<?, ? extends Open>, SyscallEvent<? extends Resolved>)
  +void sendSeccompContinue(Success, MemorySegment)
  +void sendSeccompError(Failed, MemorySegment, int)
  +FileDescriptor<SeccompNotif, Open> recvDescriptor(FileDescriptor<UnixSocket, ? extends Open>)
  +SyscallResult poll(MemorySegment, long, int)
  +SyscallResult read(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +SyscallResult write(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +SyscallResult recv(FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
  +SyscallResult ioctl(FileDescriptor<?, ? extends Open>, long, MemorySegment)
  +FileDescriptor<UnixSocket, Open> createServer(String)
  +FileDescriptor<UnixSocket, Open> accept(FileDescriptor<UnixSocket, ? extends Open>)
  +void close(FileDescriptor<?, ? extends Open>)
}
interface "SeccompResponder" as io.mazewall.profiler.engine.SeccompResponder {
  + {abstract}void sendSeccompContinue(Success, MemorySegment)
  + {abstract}void sendSeccompError(Failed, MemorySegment, int)
}
interface "SessionEvent" as io.mazewall.profiler.engine.SessionEvent {
  + {abstract}long getTimestampNanos()
  + {abstract}long getThreadId()
}
class "SessionEventLedger" as io.mazewall.profiler.engine.SessionEventLedger {
  + {static}Companion Companion
  __
  +void record(SessionEvent)
  +List<SessionEvent> dump()
}
interface "SocketLifecycleManager" as io.mazewall.profiler.engine.SocketLifecycleManager {
  + {abstract}FileDescriptor<UnixSocket, Open> createServer(String)
  + {abstract}FileDescriptor<UnixSocket, Open> accept(FileDescriptor<UnixSocket, ? extends Open>)
  + {abstract}void close(FileDescriptor<?, ? extends Open>)
  + {abstract}FileDescriptor<SeccompNotif, Open> recvDescriptor(FileDescriptor<UnixSocket, ? extends Open>)
}
class "SyscallEvent" as io.mazewall.profiler.engine.SyscallEvent<S extends SyscallEventState> {
  +int getTid()
  +String getSyscallName()
  +List<Long> getArgs()
  +List<String> getPaths()
  +List<String> getStackTrace()
  +SyscallEvent<S> copy(int, String, List<Long>, List<String>, List<String>)
}
class "SyscallEventKt" as io.mazewall.profiler.engine.SyscallEventKt {
  + {static}SyscallEvent<Resolved> resolved(SyscallEvent<? extends Raw>, List<String>)
}
interface "SyscallEventState" as io.mazewall.profiler.engine.SyscallEventState {
}
class "SyscallPathResolver" as io.mazewall.profiler.engine.SyscallPathResolver {
  +SyscallEvent<Resolved> resolve(SyscallEvent<? extends Raw>)
}
abstract class "TraceEvent" as io.mazewall.profiler.engine.TraceEvent {
  + {static}Companion Companion
  __
  + {abstract}int getTid()
  + {abstract}String getSyscallName()
  + {abstract}List<String> getStackTrace()
  +List<String> getPaths()
}
interface "TraceEventPublisher" as io.mazewall.profiler.engine.TraceEventPublisher {
  + {abstract}void sendTraceEvent(FileDescriptor<?, ? extends Open>, SyscallEvent<? extends Resolved>)
}
class "DaemonContext" as io.mazewall.profiler.internal.DaemonContext {
  +String getSocketPath()
  +Path getSocketDir()
  +Process getDaemonProcess()
  +Thread getShutdownHook()
}
class "NativeSocketInputStream" as io.mazewall.profiler.internal.NativeSocketInputStream {
  + {static}Companion Companion
  __
  +int read()
  +int read(byte[], int, int)
  +void close()
}
class "ProfilerDaemonManager" as io.mazewall.profiler.internal.ProfilerDaemonManager {
  + {static}ProfilerDaemonManager INSTANCE
  __
  +DaemonContext getOrSpawnSharedDaemon()
  +void stop()
  +void cleanupDaemon(DaemonContext)
}
class "ProfilerSocket" as io.mazewall.profiler.internal.ProfilerSocket {
  + {static}ProfilerSocket INSTANCE
  __
  +int connectWithRetry(String, int, long)
  +boolean sendDescriptor(int, int)
  +MemorySegment setupSockAddrUn(Arena, String)
}
class "ProfilerTraceListener" as io.mazewall.profiler.internal.ProfilerTraceListener {
  + {static}Companion Companion
  __
  +TraceListenerState getState()
  +void start(CountDownLatch)
  +void close()
  +void passThrough()
}
interface "TraceListenerState" as io.mazewall.profiler.internal.TraceListenerState {
}
class "IterativeProfiler" as io.mazewall.profiler.iterative.IterativeProfiler {
  + {static}IterativeProfiler INSTANCE
}
interface "IterativeProfilerState" as io.mazewall.profiler.iterative.IterativeProfilerState {
}
class "StraceProfiler" as io.mazewall.profiler.strace.StraceProfiler {
  + {static}StraceProfiler INSTANCE
}
class "StraceWorkloadRunner" as io.mazewall.profiler.strace.StraceWorkloadRunner {
  + {static}StraceWorkloadRunner INSTANCE
  __
  + {static}void main(String[])
}
io.mazewall.profiler.BillOfBehavior --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.JvmBaselineProfiles --> io.mazewall.profiler.JvmBaselineProfiles
io.mazewall.profiler.Profiler --> io.mazewall.profiler.internal.ProfilerTraceListener
io.mazewall.profiler.Profiler --> io.mazewall.profiler.Profiler
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.BillOfBehavior
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.compiler.BobCompiler --> io.mazewall.profiler.compiler.BobCompiler
io.mazewall.profiler.engine.ProfilerDaemon --> io.mazewall.profiler.engine.ProfilerDaemon
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.ProfilerDaemonState
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.SocketLifecycleManager
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.ProfilerInstaller --> io.mazewall.profiler.engine.ProfilerInstaller
io.mazewall.profiler.engine.ProfilerInstallerSession --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.ProfilerState
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SessionEventLedger
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.SocketLifecycleManager
io.mazewall.profiler.engine.RealMemoryReader .u.|> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.RealMemoryReader --> io.mazewall.profiler.engine.RealMemoryReader
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.SocketLifecycleManager
io.mazewall.profiler.engine.RealProfilerTransport --> io.mazewall.profiler.engine.RealProfilerTransport
io.mazewall.profiler.engine.SessionEventLedger --> io.mazewall.profiler.engine.SessionEvent
io.mazewall.profiler.engine.SyscallPathResolver --> io.mazewall.profiler.engine.SessionEventLedger
io.mazewall.profiler.engine.SyscallPathResolver --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.internal.ProfilerDaemonManager --> io.mazewall.profiler.internal.ProfilerDaemonManager
io.mazewall.profiler.internal.ProfilerDaemonManager --> io.mazewall.profiler.internal.DaemonContext
io.mazewall.profiler.internal.ProfilerSocket --> io.mazewall.profiler.internal.ProfilerSocket
io.mazewall.profiler.internal.ProfilerTraceListener --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.internal.ProfilerTraceListener --> io.mazewall.profiler.internal.TraceListenerState
io.mazewall.profiler.iterative.IterativeProfiler --> io.mazewall.profiler.iterative.IterativeProfiler
io.mazewall.profiler.strace.StraceProfiler --> io.mazewall.profiler.strace.StraceProfiler
io.mazewall.profiler.strace.StraceWorkloadRunner --> io.mazewall.profiler.strace.StraceWorkloadRunner
@enduml
