@startuml Profiler Class Diagram
!pragma useIntermediatePackages false
!theme spacelab
set separator none
hide empty members

class "BaselinePathProfile" as io.mazewall.profiler.BaselinePathProfile {
  +Set<String> getExactPaths()
  +Set<String> getPathPrefixes()
  +boolean matches(String)
}
class "BillOfBehavior" as io.mazewall.profiler.BillOfBehavior {
  + {static}Companion Companion
  __
  +Set<String> getOpens()
  +Set<String> getFsWritePaths()
  +Set<Syscall> getSyscalls()
  +Set<String> getExecs()
  +Set<NetworkEndpoint> getConnects()
  +Set<String> getIoUringOps()
  +Map<TraceEvent, List<StackTraceElement[]>> getStackProfile()
  +BillOfBehavior plus(BillOfBehavior)
  +BillOfBehavior filterPaths(BaselinePathProfile)
  +String toJson()
  +String toStackTracesJson()
}
class "BillOfBehaviorKt" as io.mazewall.profiler.BillOfBehaviorKt {
}
class "EbpfCapability" as io.mazewall.profiler.EbpfCapability {
  + {static}EbpfCapability INSTANCE
  __
  +EbpfLoad probe(Path, Path, Path, Path, Integer)
  +Long parseCapEff(String)
  +boolean parseInitUserNamespace(String)
  +boolean hasCap(long, int)
  +Integer parseEuid(String)
}
interface "EbpfLoad" as io.mazewall.profiler.EbpfLoad {
}
interface "FsEffect" as io.mazewall.profiler.FsEffect {
  + {static}Companion Companion
  __
  + {abstract}List<String> getPaths()
}
class "IncompleteProfileException" as io.mazewall.profiler.IncompleteProfileException {
  +ProfilingCoverage getCoverage()
}
enum "IoUringVisibility" as io.mazewall.profiler.IoUringVisibility {
  OBSERVED
  DISABLED_FOR_HYBRID
  BLIND
  BLOCKED
  UNSEEN
}
class "JvmBaselineProfiles" as io.mazewall.profiler.JvmBaselineProfiles {
  ..
  + {static}JvmBaselineProfiles INSTANCE
  __
  +BaselinePathProfile jvmBootstrapNoise()
}
class "MazewallProfiler" as io.mazewall.profiler.MazewallProfiler {
  + {static}Companion Companion
  __
  +ProfilingResult<Unit> snapshot()
  +void close()
}
class "NetworkEndpoint" as io.mazewall.profiler.NetworkEndpoint {
  +String getHost()
  +Integer getPort()
}
class "ObservationCorrelation" as io.mazewall.profiler.ObservationCorrelation {
  +int getTgid()
  +int getTid()
  +Long getKtimeNs()
  +ObservationCorrelation copy(int, int, Long)
}
enum "ObservationSource" as io.mazewall.profiler.ObservationSource {
  USER_NOTIF
  STRACE
  EBPF
}
enum "PathResolutionQuality" as io.mazewall.profiler.PathResolutionQuality {
  RESOLVED
  TRUNCATED
  FAILED
  MIXED
  NONE
}
class "ProfileEnvironment" as io.mazewall.profiler.ProfileEnvironment {
  __
  +String getKernelRelease()
  +EbpfLoad getEbpfLoad()
  +Integer getLandlockAbi()
  +Boolean getIoUringDisabled()
}
interface "ProfileEvidence" as io.mazewall.profiler.ProfileEvidence {
}
interface "ProfileObservation" as io.mazewall.profiler.ProfileObservation {
  ..
  + {static}Companion Companion
  __
  + {abstract}ObservationCorrelation getCorrelation()
  + {abstract}ObservationSource getSource()
  + {abstract}List<String> getPaths()
}
class "ProfileOptions" as io.mazewall.profiler.ProfileOptions {
  +ProfileStrategy getStrategy()
  +boolean getCaptureStacks()
  +boolean getProcessWide()
  +Boolean getIoUringDisabled()
  +Path getEbpfEventLog()
}
enum "ProfileStrategy" as io.mazewall.profiler.ProfileStrategy {
  USER_NOTIF
  STRACE
  EBPF
  HYBRID_NO_URING
  AUTO
}
class "Profiler" as io.mazewall.profiler.Profiler {
  ..
  + {static}Profiler INSTANCE
  __
  +ConcurrentHashMap<Tid, Thread> getThreadRegistry()
  +Function0<ProfilerDaemonManager> getDaemonManagerProvider()
  +void setDaemonManagerProvider(Function0<ProfilerDaemonManager>)
  +ProfilerInstallerInterface getInstallerProvider()
  +void setInstallerProvider(ProfilerInstallerInterface)
  +void shutdown()
}
class "ProfilerAckPreload" as io.mazewall.profiler.ProfilerAckPreload {
  + {static}ProfilerAckPreload INSTANCE
  __
  +List<String> getRequiredBinaryNames()
  +void ensureLoaded()
}
class "ProfilingCoverage" as io.mazewall.profiler.ProfilingCoverage {
  + {static}Companion Companion
  __
  +ProfileStrategy getStrategy()
  +String getStrategyReason()
  +boolean getProcessWide()
  +IoUringVisibility getIoUring()
  +PathResolutionQuality getPathResolution()
  +StackAttribution getStacks()
  +int getDroppedEvents()
  +boolean getDrainComplete()
  +ProfileEnvironment getEnvironment()
  +boolean getComplete()
  +List<String> getWarnings()
  +ProfileEvidence evidence()
  +ProfilingCoverage retainStricterPathResolution(ProfilingCoverage)
}
class "ProfilingResult" as io.mazewall.profiler.ProfilingResult<T> {
  +T getValue()
  +BillOfBehavior getBehavior()
  +Map<TraceEvent, List<StackTraceElement[]>> getStackProfile()
  +ProfilingCoverage getCoverage()
  +List<ProfileObservation> getObservations()
}
enum "StackAttribution" as io.mazewall.profiler.StackAttribution {
  CAPTURED
  SKIPPED
}
interface "TraceableWorkload" as io.mazewall.profiler.TraceableWorkload {
}
interface "UringOp" as io.mazewall.profiler.UringOp {
  ..
  + {static}Companion Companion
  __
  +boolean isPathBearing()
  +boolean isFilesystemMutation()
}
class "CollectorDrain" as io.mazewall.profiler.collector.CollectorDrain {
  +List<ProfileObservation> getObservations()
  +int getDroppedEvents()
  +boolean getDrainComplete()
  +IoUringVisibility getIoUring()
}
class "EbpfCollector" as io.mazewall.profiler.collector.EbpfCollector {
  +ObservationSource getSource()
  +void start()
  +CollectorDrain drain()
  +void close()
}
class "EbpfEventParser" as io.mazewall.profiler.collector.EbpfEventParser {
  + {static}EbpfEventParser INSTANCE
  __
  +EbpfParseResult parse(String)
  +ProfileObservation parseLine(String)
  +Map<String, String> parseFields(String)
}
class "EbpfParseResult" as io.mazewall.profiler.collector.EbpfParseResult {
  +List<ProfileObservation> getObservations()
  +int getDroppedLines()
}
class "ObservationMerger" as io.mazewall.profiler.collector.ObservationMerger {
  + {static}ObservationMerger INSTANCE
  __
  +CollectorDrain merge(List<CollectorDrain>)
}
interface "ProfileCollector" as io.mazewall.profiler.collector.ProfileCollector {
  + {abstract}ObservationSource getSource()
  + {abstract}void start()
  + {abstract}CollectorDrain drain()
  + {abstract}void close()
}
class "StraceCollector" as io.mazewall.profiler.collector.StraceCollector {
  +ObservationSource getSource()
  +void start()
  +CollectorDrain drain()
  +void close()
}
class "BobCompiler" as io.mazewall.profiler.compiler.BobCompiler {
  + {static}BobCompiler INSTANCE
  __
  +BillOfBehavior compile(List<? extends TraceEvent>)
  +BillOfBehavior compileObservations(List<? extends ProfileObservation>)
}
class "StraceLogParser" as io.mazewall.profiler.compiler.StraceLogParser {
  + {static}StraceLogParser INSTANCE
  __
  +List<ProfileObservation> parse(String)
  +ProfileObservation parseLine(String)
}
interface "DaemonRunner" as io.mazewall.profiler.engine.DaemonRunner {
  + {abstract}void runDaemon(String[])
}
abstract class "HandshakeSession" as io.mazewall.profiler.engine.HandshakeSession {
  + {abstract}long getNotifId()
  + {abstract}FileDescriptor<SeccompNotif, Open> getListenerFd()
}
interface "NativeIoOperations" as io.mazewall.profiler.engine.NativeIoOperations {
  + {abstract}RawSyscallOperations getRaw()
  + {abstract}SyscallResult poll(MemorySegment, long, int)
  + {abstract}SyscallResult read(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}SyscallResult write(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  + {abstract}SyscallResult recv(FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
  + {abstract}SyscallResult ioctl(FileDescriptor<?, ? extends Open>, long, MemorySegment)
  + {abstract}void close(FileDescriptor<?, ? extends Open>)
}
class "PathNormalizerHelper" as io.mazewall.profiler.engine.PathNormalizerHelper {
  + {static}PathNormalizerHelper INSTANCE
  __
  +String normalizePath(String)
  +boolean pathStartsWith(String, String)
}
class "PollEvents" as io.mazewall.profiler.engine.PollEvents {
  +short getSocketRevents()
  +short getListenerRevents()
}
class "ProfilerDaemon" as io.mazewall.profiler.engine.ProfilerDaemon {
  + {static}ProfilerDaemon INSTANCE
  __
  +DaemonRunner getRunner()
  +void setRunner(DaemonRunner)
  + {static}void main(String[])
}
class "ProfilerDaemonEngine" as io.mazewall.profiler.engine.ProfilerDaemonEngine {
  + {static}Companion Companion
  +CopyOnWriteArrayList<FileDescriptor<UnixSocket, Open>> clientSockets
  __
  +UnixListenDaemonState getState()
  +void run(Function0<Unit>)
  +void handleConnection(FileDescriptor<UnixSocket, ? extends Open>)
  +void handleNewConnection(FileDescriptor<UnixSocket, ? extends Open>)
  +void triggerGlobalShutdown(String)
}
class "ProfilerInstaller" as io.mazewall.profiler.engine.ProfilerInstaller {
  + {static}ProfilerInstaller INSTANCE
  __
  +void installProfilingFilterForThread(String, PolicyDefinition<?>, List<TraceEvent>, Map<TraceEvent, List<StackTraceElement[]>>, Map<String, Long>, boolean, Function1<? super String, Integer>, Function5<? super Integer, ? super List<TraceEvent>, ? super Map<TraceEvent, List<StackTraceElement[]>>, ? super Map<String, Long>, ? super CountDownLatch, Unit>)
}
interface "ProfilerInstallerInterface" as io.mazewall.profiler.engine.ProfilerInstallerInterface {
  + {abstract}void installProfilingFilterForThread(String, PolicyDefinition<?>, List<TraceEvent>, Map<TraceEvent, List<StackTraceElement[]>>, Map<String, Long>, boolean, Function5<? super Integer, ? super List<TraceEvent>, ? super Map<TraceEvent, List<StackTraceElement[]>>, ? super Map<String, Long>, ? super CountDownLatch, Unit>)
}
class "ProfilerInstallerSession" as io.mazewall.profiler.engine.ProfilerInstallerSession {
  +void install()
}
interface "ProfilerInstallerState" as io.mazewall.profiler.engine.ProfilerInstallerState {
}
interface "ProfilerMemoryReader" as io.mazewall.profiler.engine.ProfilerMemoryReader {
  +String readStringFromProcess(NativeArena, int, long, int)
  +String readString(NativeArena, int, long, int)
  +byte[] readBytes(NativeArena, int, long, int)
  +String resolveLink(NativeArena, int, String)
}
interface "ProfilerSessionEvent" as io.mazewall.profiler.engine.ProfilerSessionEvent {
}
class "ProfilerSessionHandler" as io.mazewall.profiler.engine.ProfilerSessionHandler {
  + {static}Companion Companion
  __
  +SessionEventLedger getLedger()
  +ManagedSegment getAckBuf()
  +ManagedSegment getSocketPollFd()
  +ProfilerState getState()
  +void close()
  +NotifResult processNotification(NativeArena, ManagedSegment, ManagedSegment, FileDescriptor<SeccompNotif, ? extends Open>, FileDescriptor<UnixSocket, ? extends Open>)
}
class "ProfilerSessionMachine" as io.mazewall.profiler.engine.ProfilerSessionMachine {
  + {static}ProfilerSessionMachine INSTANCE
  __
  +ProfilerSessionTransition evaluate(ProfilerState, ProfilerSessionEvent)
}
class "ProfilerSessionTransition" as io.mazewall.profiler.engine.ProfilerSessionTransition {
  +ProfilerState getState()
  +boolean getTerminate()
  +boolean getPassThrough()
}
interface "ProfilerState" as io.mazewall.profiler.engine.ProfilerState {
  + {abstract}FileDescriptor<UnixSocket, Open> getSocketFd()
  + {abstract}FileDescriptor<SeccompNotif, Open> getListenerFd()
}
interface "ProfilerTransport" as io.mazewall.profiler.engine.ProfilerTransport {
}
class "ProfilerTransportKt" as io.mazewall.profiler.engine.ProfilerTransportKt {
}
class "RealDaemonRunner" as io.mazewall.profiler.engine.RealDaemonRunner {
  +void runDaemon(String[])
}
class "RealMemoryReader" as io.mazewall.profiler.engine.RealMemoryReader {
  + {static}RealMemoryReader INSTANCE
  __
  +String readStringFromProcess(NativeArena, int, long, int)
  +String readString(NativeArena, int, long, int)
  +byte[] readBytes(NativeArena, int, long, int)
  +String resolveLink(NativeArena, int, String)
}
class "RealProfilerInstaller" as io.mazewall.profiler.engine.RealProfilerInstaller {
  + {static}RealProfilerInstaller INSTANCE
  __
  +void installProfilingFilterForThread(String, PolicyDefinition<?>, List<TraceEvent>, Map<TraceEvent, List<StackTraceElement[]>>, Map<String, Long>, boolean, Function5<? super Integer, ? super List<TraceEvent>, ? super Map<TraceEvent, List<StackTraceElement[]>>, ? super Map<String, Long>, ? super CountDownLatch, Unit>)
}
class "RealProfilerTransport" as io.mazewall.profiler.engine.RealProfilerTransport {
  + {static}RealProfilerTransport INSTANCE
  __
  +RawSyscallOperations getRaw()
  +void sendTraceEvent(Arena, FileDescriptor<?, ? extends Open>, SyscallEvent<? extends Resolved>)
  +void sendSeccompContinue(Arena, Success, MemorySegment)
  +void sendSeccompError(Arena, Failed, MemorySegment, int)
  +FileDescriptor<UnixSocket, Open> connect(String)
  +boolean sendDescriptor(FileDescriptor<UnixSocket, ? extends Open>, FileDescriptor<?, ? extends Open>)
  +FileDescriptor<SeccompNotif, Open> recvDescriptor(FileDescriptor<UnixSocket, ? extends Open>)
  +SyscallResult poll(MemorySegment, long, int)
  +SyscallResult read(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +SyscallResult write(FileDescriptor<?, ? extends Open>, MemorySegment, long)
  +SyscallResult recv(FileDescriptor<?, ? extends Open>, MemorySegment, long, int)
  +SyscallResult ioctl(FileDescriptor<?, ? extends Open>, long, MemorySegment)
  +FileDescriptor<UnixSocket, Open> createUnixServer(String)
  +FileDescriptor<UnixSocket, Open> accept(FileDescriptor<UnixSocket, ? extends Open>)
  +void close(FileDescriptor<?, ? extends Open>)
}
class "RealSeccompNotificationParser" as io.mazewall.profiler.engine.RealSeccompNotificationParser {
  + {static}RealSeccompNotificationParser INSTANCE
  __
  +SeccompNotification readNotif(ManagedSegment)
  +PollEvents readPollEvents(ManagedSegment)
  +void writeSocketPoll(ManagedSegment, int, short)
}
class "SeccompNotification" as io.mazewall.profiler.engine.SeccompNotification {
  +long getId()
  +int getPid()
  +int getNr()
  +long[] getArgs()
}
interface "SeccompNotificationParser" as io.mazewall.profiler.engine.SeccompNotificationParser {
  + {abstract}SeccompNotification readNotif(ManagedSegment)
  + {abstract}PollEvents readPollEvents(ManagedSegment)
  + {abstract}void writeSocketPoll(ManagedSegment, int, short)
}
interface "SeccompResponder" as io.mazewall.profiler.engine.SeccompResponder {
  + {abstract}void sendSeccompContinue(Arena, Success, MemorySegment)
  + {abstract}void sendSeccompError(Arena, Failed, MemorySegment, int)
}
interface "SessionEvent" as io.mazewall.profiler.engine.SessionEvent {
  + {abstract}long getTimestampNanos()
  + {abstract}long getThreadId()
}
class "SessionEventLedger" as io.mazewall.profiler.engine.SessionEventLedger {
  + {static}Companion Companion
  __
  +void record(SessionEvent)
  +List<SessionEvent> dump()
}
class "SyscallEvent" as io.mazewall.profiler.engine.SyscallEvent<S extends SyscallEventState> {
  +int getTid()
  +String getSyscallName()
  +List<Long> getArgs()
  +List<String> getPaths()
  +List<String> getStackTrace()
  +SyscallEvent<S> copy(int, String, List<Long>, List<String>, List<String>)
}
class "SyscallEventKt" as io.mazewall.profiler.engine.SyscallEventKt {
  + {static}SyscallEvent<Resolved> resolved(SyscallEvent<? extends Raw>, List<String>)
}
interface "SyscallEventState" as io.mazewall.profiler.engine.SyscallEventState {
}
class "SyscallPathResolver" as io.mazewall.profiler.engine.SyscallPathResolver {
  +SyscallEvent<Resolved> resolve(NativeArena, SyscallEvent<? extends Raw>)
  +List<String> resolvePaths(NativeArena, int, String, long[])
  +List<String> resolvePaths(NativeArena, int, String, List<Long>)
}
abstract class "TraceEvent" as io.mazewall.profiler.engine.TraceEvent {
  + {static}Companion Companion
  __
  + {abstract}int getTid()
  + {abstract}String getSyscallName()
  + {abstract}List<String> getStackTrace()
  +List<String> getPaths()
  +StackTraceElement[] getJvmStackTrace()
  +void setJvmStackTrace(StackTraceElement[])
}
interface "TraceEventPublisher" as io.mazewall.profiler.engine.TraceEventPublisher {
  + {abstract}void sendTraceEvent(Arena, FileDescriptor<?, ? extends Open>, SyscallEvent<? extends Resolved>)
}
class "TransportNativeEngine" as io.mazewall.profiler.engine.TransportNativeEngine {
  +RawSyscallOperations getRaw()
  +NativeFileSystem getFileSystem()
  +NativeProcess getProcess()
  +NativeNetworking getNetworking()
  +NativeMemory getMemory()
}
class "TransportNativeMemory" as io.mazewall.profiler.engine.TransportNativeMemory {
  +SyscallResult read(FileDescriptor<?, ? extends Open>, ManagedSegment, long)
  +SyscallResult write(FileDescriptor<?, ? extends Open>, ManagedSegment, long)
  +SyscallResult processVmReadv(int, ManagedSegment, long, ManagedSegment, long, long)
  +SyscallResult processVmWritev(int, ManagedSegment, long, ManagedSegment, long, long)
  +ManagedSegment newSockFProg(NativeArena, List<? extends BpfInstruction>)
}
class "DaemonContext" as io.mazewall.profiler.internal.DaemonContext {
  +String getSocketPath()
  +Path getSocketDir()
  +Process getDaemonProcess()
  +Thread getShutdownHook()
}
class "DescendantStrace" as io.mazewall.profiler.internal.DescendantStrace {
  + {static}DescendantStrace INSTANCE
  __
  +BillOfBehavior compile(Class<? extends TraceableWorkload>)
}
class "NativeSocketInputStream" as io.mazewall.profiler.internal.NativeSocketInputStream {
  + {static}Companion Companion
  __
  +int read()
  +int read(byte[], int, int)
  +void close()
}
class "ProfilerDaemonManager" as io.mazewall.profiler.internal.ProfilerDaemonManager {
  + {static}Companion Companion
  __
  +DaemonContext getOrSpawnSharedDaemon()
  +void stop()
  +void cleanupDaemon(DaemonContext)
  + {static}ProfilerDaemonManager getInstance()
}
class "ProfilerSocket" as io.mazewall.profiler.internal.ProfilerSocket {
  + {static}ProfilerSocket INSTANCE
  __
  +int connectWithRetry(String, int, long)
  +boolean sendDescriptor(int, int)
}
class "ProfilerTraceListener" as io.mazewall.profiler.internal.ProfilerTraceListener {
  + {static}Companion Companion
  __
  +TraceEventQueue getEventQueue()
  +Channel<TraceEvent> getEventChannel()
  +Flow<TraceEvent> getEventFlow()
  +TraceListenerState getState()
  +boolean getDrainComplete()
  +void start(CountDownLatch)
  +void close()
  +void passThrough()
}
class "TraceEventQueue" as io.mazewall.profiler.internal.TraceEventQueue {
  + {static}Companion Companion
  + {static}int DEFAULT_CAPACITY
  __
  +Channel<TraceEvent> getChannel()
  +long getDroppedCount()
  +boolean offer(TraceEvent)
  +void close()
}
interface "TraceListenerState" as io.mazewall.profiler.internal.TraceListenerState {
}
class "IterativeProfiler" as io.mazewall.profiler.iterative.IterativeProfiler {
  + {static}IterativeProfiler INSTANCE
  __
  +IterativeTaskExecutor getTaskExecutor()
  +void setTaskExecutor(IterativeTaskExecutor)
  +void registerPhrase(String)
  +void registerRegex(Regex)
  +List<String> getRegisteredPhrases()
  +List<Regex> getRegisteredRegexes()
  +void resetToDefaults()
}
interface "IterativeProfilerState" as io.mazewall.profiler.iterative.IterativeProfilerState {
}
interface "IterativeTaskExecutor" as io.mazewall.profiler.iterative.IterativeTaskExecutor {
  + {abstract}Throwable executeTask(Policy<?, ? extends Uncompiled>, Runnable)
}
class "RealIterativeTaskExecutor" as io.mazewall.profiler.iterative.RealIterativeTaskExecutor {
  + {static}RealIterativeTaskExecutor INSTANCE
  __
  +Throwable executeTask(Policy<?, ? extends Uncompiled>, Runnable)
}
class "StraceProfiler" as io.mazewall.profiler.strace.StraceProfiler {
  + {static}StraceProfiler INSTANCE
}
class "StraceWorkloadRunner" as io.mazewall.profiler.strace.StraceWorkloadRunner {
  + {static}StraceWorkloadRunner INSTANCE
  __
  + {static}void main(String[])
}
class "DiagnosticTriageRunner" as io.mazewall.profiler.triage.DiagnosticTriageRunner {
  + {static}DiagnosticTriageRunner INSTANCE
  __
  + {static}void main(String[])
}
io.mazewall.profiler.BillOfBehavior --> io.mazewall.profiler.NetworkEndpoint
io.mazewall.profiler.BillOfBehavior --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.EbpfCapability --> io.mazewall.profiler.EbpfCapability
io.mazewall.profiler.IncompleteProfileException --> io.mazewall.profiler.ProfilingCoverage
io.mazewall.profiler.JvmBaselineProfiles --> io.mazewall.profiler.JvmBaselineProfiles
io.mazewall.profiler.MazewallProfiler --> io.mazewall.profiler.ProfileStrategy
io.mazewall.profiler.MazewallProfiler --> io.mazewall.profiler.ProfileOptions
io.mazewall.profiler.MazewallProfiler --> io.mazewall.profiler.ProfilingResult
io.mazewall.profiler.MazewallProfiler --> io.mazewall.profiler.ProfileEnvironment
io.mazewall.profiler.ProfileEnvironment --> io.mazewall.profiler.EbpfLoad
io.mazewall.profiler.ProfileOptions --> io.mazewall.profiler.ProfileStrategy
io.mazewall.profiler.Profiler --> io.mazewall.profiler.internal.ProfilerTraceListener
io.mazewall.profiler.Profiler --> io.mazewall.profiler.Profiler
io.mazewall.profiler.Profiler --> io.mazewall.profiler.internal.ProfilerDaemonManager
io.mazewall.profiler.Profiler --> io.mazewall.profiler.engine.ProfilerInstallerInterface
io.mazewall.profiler.ProfilerAckPreload --> io.mazewall.profiler.ProfilerAckPreload
io.mazewall.profiler.ProfilingCoverage --> io.mazewall.profiler.IoUringVisibility
io.mazewall.profiler.ProfilingCoverage --> io.mazewall.profiler.ProfileStrategy
io.mazewall.profiler.ProfilingCoverage --> io.mazewall.profiler.StackAttribution
io.mazewall.profiler.ProfilingCoverage --> io.mazewall.profiler.ProfileEnvironment
io.mazewall.profiler.ProfilingCoverage --> io.mazewall.profiler.PathResolutionQuality
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.BillOfBehavior
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.ProfileObservation
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.ProfilingCoverage
io.mazewall.profiler.ProfilingResult --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.collector.CollectorDrain --> io.mazewall.profiler.IoUringVisibility
io.mazewall.profiler.collector.CollectorDrain --> io.mazewall.profiler.ProfileObservation
io.mazewall.profiler.collector.EbpfCollector .u.|> io.mazewall.profiler.collector.ProfileCollector
io.mazewall.profiler.collector.EbpfCollector --> io.mazewall.profiler.ObservationSource
io.mazewall.profiler.collector.EbpfCollector --> io.mazewall.profiler.EbpfLoad
io.mazewall.profiler.collector.EbpfEventParser --> io.mazewall.profiler.collector.EbpfEventParser
io.mazewall.profiler.collector.EbpfParseResult --> io.mazewall.profiler.ProfileObservation
io.mazewall.profiler.collector.ObservationMerger --> io.mazewall.profiler.collector.ObservationMerger
io.mazewall.profiler.collector.StraceCollector .u.|> io.mazewall.profiler.collector.ProfileCollector
io.mazewall.profiler.collector.StraceCollector --> io.mazewall.profiler.TraceableWorkload
io.mazewall.profiler.collector.StraceCollector --> io.mazewall.profiler.ObservationSource
io.mazewall.profiler.compiler.BobCompiler --> io.mazewall.profiler.compiler.BobCompiler
io.mazewall.profiler.compiler.StraceLogParser --> io.mazewall.profiler.compiler.StraceLogParser
io.mazewall.profiler.engine.PathNormalizerHelper --> io.mazewall.profiler.engine.PathNormalizerHelper
io.mazewall.profiler.engine.ProfilerDaemon --> io.mazewall.profiler.engine.DaemonRunner
io.mazewall.profiler.engine.ProfilerDaemon --> io.mazewall.profiler.engine.ProfilerDaemon
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.ProfilerDaemonEngine --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.ProfilerInstaller --> io.mazewall.profiler.engine.ProfilerInstaller
io.mazewall.profiler.engine.ProfilerInstallerSession --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SeccompNotificationParser
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SyscallPathResolver
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.ProfilerState
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.SessionEventLedger
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.ProfilerSessionHandler --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.ProfilerSessionMachine --> io.mazewall.profiler.engine.ProfilerSessionMachine
io.mazewall.profiler.engine.ProfilerSessionTransition --> io.mazewall.profiler.engine.ProfilerState
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.ProfilerTransport .u.|> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.RealDaemonRunner .u.|> io.mazewall.profiler.engine.DaemonRunner
io.mazewall.profiler.engine.RealDaemonRunner --> io.mazewall.profiler.engine.ProfilerDaemonEngine
io.mazewall.profiler.engine.RealMemoryReader .u.|> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.RealMemoryReader --> io.mazewall.profiler.engine.RealMemoryReader
io.mazewall.profiler.engine.RealProfilerInstaller .u.|> io.mazewall.profiler.engine.ProfilerInstallerInterface
io.mazewall.profiler.engine.RealProfilerInstaller --> io.mazewall.profiler.engine.RealProfilerInstaller
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.TraceEventPublisher
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.SeccompResponder
io.mazewall.profiler.engine.RealProfilerTransport .u.|> io.mazewall.profiler.engine.NativeIoOperations
io.mazewall.profiler.engine.RealProfilerTransport --> io.mazewall.profiler.engine.RealProfilerTransport
io.mazewall.profiler.engine.RealSeccompNotificationParser .u.|> io.mazewall.profiler.engine.SeccompNotificationParser
io.mazewall.profiler.engine.RealSeccompNotificationParser --> io.mazewall.profiler.engine.RealSeccompNotificationParser
io.mazewall.profiler.engine.SessionEventLedger --> io.mazewall.profiler.engine.SessionEvent
io.mazewall.profiler.engine.SyscallPathResolver --> io.mazewall.profiler.engine.SessionEventLedger
io.mazewall.profiler.engine.SyscallPathResolver --> io.mazewall.profiler.engine.ProfilerMemoryReader
io.mazewall.profiler.engine.TransportNativeEngine --> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.engine.TransportNativeMemory --> io.mazewall.profiler.engine.ProfilerTransport
io.mazewall.profiler.internal.DescendantStrace --> io.mazewall.profiler.internal.DescendantStrace
io.mazewall.profiler.internal.ProfilerDaemonManager --> io.mazewall.profiler.internal.ProfilerDaemonManager
io.mazewall.profiler.internal.ProfilerDaemonManager --> io.mazewall.profiler.internal.DaemonContext
io.mazewall.profiler.internal.ProfilerSocket --> io.mazewall.profiler.internal.ProfilerSocket
io.mazewall.profiler.internal.ProfilerTraceListener --> io.mazewall.profiler.internal.TraceEventQueue
io.mazewall.profiler.internal.ProfilerTraceListener --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.internal.ProfilerTraceListener --> io.mazewall.profiler.internal.TraceListenerState
io.mazewall.profiler.internal.TraceEventQueue --> io.mazewall.profiler.engine.TraceEvent
io.mazewall.profiler.iterative.IterativeProfiler --> io.mazewall.profiler.iterative.IterativeProfiler
io.mazewall.profiler.iterative.IterativeProfiler --> io.mazewall.profiler.iterative.IterativeTaskExecutor
io.mazewall.profiler.iterative.RealIterativeTaskExecutor .u.|> io.mazewall.profiler.iterative.IterativeTaskExecutor
io.mazewall.profiler.iterative.RealIterativeTaskExecutor --> io.mazewall.profiler.iterative.RealIterativeTaskExecutor
io.mazewall.profiler.strace.StraceProfiler --> io.mazewall.profiler.strace.StraceProfiler
io.mazewall.profiler.strace.StraceWorkloadRunner --> io.mazewall.profiler.strace.StraceWorkloadRunner
io.mazewall.profiler.triage.DiagnosticTriageRunner --> io.mazewall.profiler.triage.DiagnosticTriageRunner
@enduml
