package io.mazewall.core

import java.util.Locale

/**
 * High-level syscall identifiers. Each variant resolves to an architecture-specific
 * syscall number via [Arch]. Syscalls unavailable on a given architecture (e.g. [OPEN]
 * on aarch64) are represented as -1 and silently skipped during filter construction.
 */
enum class Syscall {
    FORK,
    VFORK,
    CLONE,
    CLONE3,
    EXECVE,
    EXECVEAT,
    CONNECT,
    BIND,
    LISTEN,
    ACCEPT,
    ACCEPT4,
    SENDTO,
    SENDMSG,
    RECVFROM,
    GETSOCKOPT,
    SETSOCKOPT,
    GETSOCKNAME,
    GETPEERNAME,
    SENDMMSG,
    RECVMMSG,
    OPEN,
    OPENAT,
    OPENAT2,
    MMAP,
    MPROTECT,
    PKEY_MPROTECT,
    MADVISE,
    PTRACE,
    SOCKET,
    INIT_MODULE,
    FINIT_MODULE,
    MEMFD_CREATE,
    IO_URING_SETUP,
    IO_URING_ENTER,
    BPF,
    PROCESS_VM_WRITEV,
    PROCESS_VM_READV,
    USERFAULTFD,
    UNSHARE,
    SETNS,
    MOUNT,
    UMOUNT2,
    PIVOT_ROOT,
    CHROOT,
    IOCTL,
    PRCTL,
    ARCH_PRCTL,
    READ,
    WRITE,
    CLOSE,
    FSTAT,
    LSEEK,
    MUNMAP,
    BRK,
    RT_SIGACTION,
    RT_SIGPROCMASK,
    RT_SIGRETURN,
    PREAD64,
    PWRITE64,
    FCNTL,
    FUTEX,
    SCHED_YIELD,
    GETRANDOM,
    CLOCK_GETTIME,
    EXIT,
    EXIT_GROUP,
    GETPID,
    GETPPID,
    GETUID,
    GETEUID,
    GETGID,
    GETEGID,
    GETTID,
    GETCWD,
    UMASK,
    CHOWN,
    LCHOWN,
    FCHOWN,
    FCHOWNAT,
    UTIME,
    UTIMES,
    UTIMENSAT,
    MKDIR,
    MKDIRAT,
    RMDIR,
    RENAME,
    RENAMEAT,
    RENAMEAT2,
    LINK,
    LINKAT,
    UNLINK,
    UNLINKAT,
    SYMLINK,
    SYMLINKAT,
    READLINK,
    READLINKAT,
    CHMOD,
    FCHMOD,
    FCHMODAT,
    FSTATAT,
    STATX,
    FSYNC,
    FDATASYNC,
    CREAT,
    TRUNCATE,
    FTRUNCATE,
    PAUSE,
    NANOSLEEP,
    ;

    /** Returns the syscall number for the given [arch], or -1 if not available. */
    fun numberFor(arch: Arch): Int = SyscallNumberResolver.numberFor(this, arch)

    public companion object {
        /** Null if [name] is not a [Syscall] enum constant (e.g. recvmsg). */
        public fun tryParse(name: String): Syscall? = entries.find { it.name == name.uppercase(Locale.US) }
    }
}
