services:
    unprotected:
        image: vulnerable-web-app-unprotected:latest
        build:
            context: .
            dockerfile: Containerfile
            cache_from:
                - vulnerable-web-app-unprotected:latest
        ports:
            - "8082:8080"
        environment:
            - MAZEWALL_ENABLED=false
        annotations:
            io.podman.annotations.seccomp: ${PWD}/infra/dev/podman-seccomp.json

    protected:
        image: vulnerable-web-app-protected:latest
        build:
            context: .
            dockerfile: Containerfile
            cache_from:
                - vulnerable-web-app-protected:latest
        ports:
            - "8081:8081"
        environment:
            - MAZEWALL_ENABLED=true
            - MAZEWALL_PROFILE=true
            - SERVER_PORT=8081
            - JAVA_TOOL_OPTIONS=-Dmazewall.sbob.path=/app/output/sbob.json
        volumes:
            - ../output:/app/output:rw
        annotations:
            io.podman.annotations.seccomp: ${PWD}/infra/dev/podman-seccomp.json
